/**
 ** This file was automatically generated by the Cyclone scheme compiler
 ** http://justinethier.github.io/cyclone/
 **
 ** (c) 2014-2020 Justin Ethier
 ** Version 0.19 
 **
 **/

#define closcall1(td, clo,a1) \
if (obj_is_not_closure(clo)) { \
   Cyc_apply(td, 0, (closure)(a1), clo); \
} else { \
   ((clo)->fn)(td, 1, clo,a1);\
}
#define return_closcall1(td, clo,a1) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[1]; buf[0] = a1;\
     GC(td, clo, buf, 1); \
     return; \
 } else {\
     closcall1(td, (closure) (clo),a1); \
     return;\
 } \
}

#define continue_or_gc1(td, clo,a1) { \
 char *top = alloca(sizeof(char)); \
 if (stack_overflow(top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[1]; buf[0] = a1;\
     GC(td, clo, buf, 1); \
     return; \
 } else {\
     continue;\
 } \
}

#define return_direct1(td, _fn,a1) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[1]; buf[0] = a1; \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 1); \
     return; \
 } else { \
     (_fn)(td, 1, (closure)_fn,a1); \
 }}

#define return_direct_with_clo1(td, clo, _fn,a1) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[1]; buf[0] = a1;\
     GC(td, clo, buf, 1); \
     return; \
 } else { \
     (_fn)(td, 1, (closure)(clo),a1); \
 }}

#define closcall2(td, clo,a1,a2) \
if (obj_is_not_closure(clo)) { \
   Cyc_apply(td, 1, (closure)(a1), clo,a2); \
} else { \
   ((clo)->fn)(td, 2, clo,a1,a2);\
}
#define return_closcall2(td, clo,a1,a2) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[2]; buf[0] = a1;buf[1] = a2;\
     GC(td, clo, buf, 2); \
     return; \
 } else {\
     closcall2(td, (closure) (clo),a1,a2); \
     return;\
 } \
}

#define continue_or_gc2(td, clo,a1,a2) { \
 char *top = alloca(sizeof(char)); \
 if (stack_overflow(top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[2]; buf[0] = a1;buf[1] = a2;\
     GC(td, clo, buf, 2); \
     return; \
 } else {\
     continue;\
 } \
}

#define return_direct2(td, _fn,a1,a2) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[2]; buf[0] = a1;buf[1] = a2; \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 2); \
     return; \
 } else { \
     (_fn)(td, 2, (closure)_fn,a1,a2); \
 }}

#define return_direct_with_clo2(td, clo, _fn,a1,a2) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[2]; buf[0] = a1;buf[1] = a2;\
     GC(td, clo, buf, 2); \
     return; \
 } else { \
     (_fn)(td, 2, (closure)(clo),a1,a2); \
 }}

#define closcall3(td, clo,a1,a2,a3) \
if (obj_is_not_closure(clo)) { \
   Cyc_apply(td, 2, (closure)(a1), clo,a2,a3); \
} else { \
   ((clo)->fn)(td, 3, clo,a1,a2,a3);\
}
#define return_closcall3(td, clo,a1,a2,a3) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3;\
     GC(td, clo, buf, 3); \
     return; \
 } else {\
     closcall3(td, (closure) (clo),a1,a2,a3); \
     return;\
 } \
}

#define continue_or_gc3(td, clo,a1,a2,a3) { \
 char *top = alloca(sizeof(char)); \
 if (stack_overflow(top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3;\
     GC(td, clo, buf, 3); \
     return; \
 } else {\
     continue;\
 } \
}

#define return_direct3(td, _fn,a1,a2,a3) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3; \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 3); \
     return; \
 } else { \
     (_fn)(td, 3, (closure)_fn,a1,a2,a3); \
 }}

#define return_direct_with_clo3(td, clo, _fn,a1,a2,a3) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3;\
     GC(td, clo, buf, 3); \
     return; \
 } else { \
     (_fn)(td, 3, (closure)(clo),a1,a2,a3); \
 }}

#define closcall4(td, clo,a1,a2,a3,a4) \
if (obj_is_not_closure(clo)) { \
   Cyc_apply(td, 3, (closure)(a1), clo,a2,a3,a4); \
} else { \
   ((clo)->fn)(td, 4, clo,a1,a2,a3,a4);\
}
#define return_closcall4(td, clo,a1,a2,a3,a4) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[4]; buf[0] = a1;buf[1] = a2;buf[2] = a3;buf[3] = a4;\
     GC(td, clo, buf, 4); \
     return; \
 } else {\
     closcall4(td, (closure) (clo),a1,a2,a3,a4); \
     return;\
 } \
}

#define continue_or_gc4(td, clo,a1,a2,a3,a4) { \
 char *top = alloca(sizeof(char)); \
 if (stack_overflow(top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[4]; buf[0] = a1;buf[1] = a2;buf[2] = a3;buf[3] = a4;\
     GC(td, clo, buf, 4); \
     return; \
 } else {\
     continue;\
 } \
}

#define return_direct4(td, _fn,a1,a2,a3,a4) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[4]; buf[0] = a1;buf[1] = a2;buf[2] = a3;buf[3] = a4; \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 4); \
     return; \
 } else { \
     (_fn)(td, 4, (closure)_fn,a1,a2,a3,a4); \
 }}

#define return_direct_with_clo4(td, clo, _fn,a1,a2,a3,a4) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[4]; buf[0] = a1;buf[1] = a2;buf[2] = a3;buf[3] = a4;\
     GC(td, clo, buf, 4); \
     return; \
 } else { \
     (_fn)(td, 4, (closure)(clo),a1,a2,a3,a4); \
 }}

#define closcall5(td, clo,a1,a2,a3,a4,a5) \
if (obj_is_not_closure(clo)) { \
   Cyc_apply(td, 4, (closure)(a1), clo,a2,a3,a4,a5); \
} else { \
   ((clo)->fn)(td, 5, clo,a1,a2,a3,a4,a5);\
}
#define return_closcall5(td, clo,a1,a2,a3,a4,a5) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[5]; buf[0] = a1;buf[1] = a2;buf[2] = a3;buf[3] = a4;buf[4] = a5;\
     GC(td, clo, buf, 5); \
     return; \
 } else {\
     closcall5(td, (closure) (clo),a1,a2,a3,a4,a5); \
     return;\
 } \
}

#define continue_or_gc5(td, clo,a1,a2,a3,a4,a5) { \
 char *top = alloca(sizeof(char)); \
 if (stack_overflow(top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[5]; buf[0] = a1;buf[1] = a2;buf[2] = a3;buf[3] = a4;buf[4] = a5;\
     GC(td, clo, buf, 5); \
     return; \
 } else {\
     continue;\
 } \
}

#define return_direct5(td, _fn,a1,a2,a3,a4,a5) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[5]; buf[0] = a1;buf[1] = a2;buf[2] = a3;buf[3] = a4;buf[4] = a5; \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 5); \
     return; \
 } else { \
     (_fn)(td, 5, (closure)_fn,a1,a2,a3,a4,a5); \
 }}

#define return_direct_with_clo5(td, clo, _fn,a1,a2,a3,a4,a5) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[5]; buf[0] = a1;buf[1] = a2;buf[2] = a3;buf[3] = a4;buf[4] = a5;\
     GC(td, clo, buf, 5); \
     return; \
 } else { \
     (_fn)(td, 5, (closure)(clo),a1,a2,a3,a4,a5); \
 }}

#define closcall6(td, clo,a1,a2,a3,a4,a5,a6) \
if (obj_is_not_closure(clo)) { \
   Cyc_apply(td, 5, (closure)(a1), clo,a2,a3,a4,a5,a6); \
} else { \
   ((clo)->fn)(td, 6, clo,a1,a2,a3,a4,a5,a6);\
}
#define return_closcall6(td, clo,a1,a2,a3,a4,a5,a6) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[6]; buf[0] = a1;buf[1] = a2;buf[2] = a3;buf[3] = a4;buf[4] = a5;buf[5] = a6;\
     GC(td, clo, buf, 6); \
     return; \
 } else {\
     closcall6(td, (closure) (clo),a1,a2,a3,a4,a5,a6); \
     return;\
 } \
}

#define continue_or_gc6(td, clo,a1,a2,a3,a4,a5,a6) { \
 char *top = alloca(sizeof(char)); \
 if (stack_overflow(top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[6]; buf[0] = a1;buf[1] = a2;buf[2] = a3;buf[3] = a4;buf[4] = a5;buf[5] = a6;\
     GC(td, clo, buf, 6); \
     return; \
 } else {\
     continue;\
 } \
}

#define return_direct6(td, _fn,a1,a2,a3,a4,a5,a6) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[6]; buf[0] = a1;buf[1] = a2;buf[2] = a3;buf[3] = a4;buf[4] = a5;buf[5] = a6; \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 6); \
     return; \
 } else { \
     (_fn)(td, 6, (closure)_fn,a1,a2,a3,a4,a5,a6); \
 }}

#define return_direct_with_clo6(td, clo, _fn,a1,a2,a3,a4,a5,a6) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[6]; buf[0] = a1;buf[1] = a2;buf[2] = a3;buf[3] = a4;buf[4] = a5;buf[5] = a6;\
     GC(td, clo, buf, 6); \
     return; \
 } else { \
     (_fn)(td, 6, (closure)(clo),a1,a2,a3,a4,a5,a6); \
 }}

#include "cyclone/types.h"
object __glo_lib_91init_117libsindex_libs_index = NULL;
object __glo_unregister_91installed_91package_67_libs_index = NULL;
object __glo_register_91installed_91package_67_libs_index = NULL;
object __glo_get_91local_91index_libs_index = NULL;
object __glo_local_91index_91contains_127_libs_index = NULL;
object __glo__85default_91local_91index_85_libs_index = NULL;
object __glo_pkg_91info_libs_index = NULL;
object __glo_get_91index_libs_index = NULL;
object __glo__85default_91index_91url_85_libs_index = NULL;
extern object __glo_member_scheme_base;
extern object __glo_assoc_scheme_base;
extern object __glo_cons_91source_scheme_base;
extern object __glo_syntax_91rules_scheme_base;
extern object __glo_letrec_85_scheme_base;
extern object __glo_guard_scheme_base;
extern object __glo_guard_91aux_scheme_base;
extern object __glo_define_91record_91type_scheme_base;
extern object __glo_record_127_scheme_base;
extern object __glo_is_91a_127_scheme_base;
extern object __glo_register_91simple_91type_scheme_base;
extern object __glo_make_91type_91predicate_scheme_base;
extern object __glo_make_91constructor_scheme_base;
extern object __glo_make_91constructor_95args_scheme_base;
extern object __glo_make_91getter_scheme_base;
extern object __glo_make_91setter_scheme_base;
extern object __glo_slot_91ref_scheme_base;
extern object __glo_slot_91set_67_scheme_base;
extern object __glo_type_91slot_91offset_scheme_base;
extern object __glo_receive_scheme_base;
extern object __glo_abs_scheme_base;
extern object __glo_max_scheme_base;
extern object __glo_min_scheme_base;
extern object __glo_modulo_scheme_base;
extern object __glo_floor_91remainder_scheme_base;
extern object __glo_even_127_scheme_base;
extern object __glo_exact_91integer_127_scheme_base;
extern object __glo_exact_91integer_91sqrt_scheme_base;
extern object __glo_exact_127_scheme_base;
extern object __glo_inexact_127_scheme_base;
extern object __glo_odd_127_scheme_base;
extern object __glo_complex_127_scheme_base;
extern object __glo_rational_127_scheme_base;
extern object __glo_bignum_127_scheme_base;
extern object __glo_gcd_scheme_base;
extern object __glo_lcm_scheme_base;
extern object __glo_quotient_scheme_base;
extern object __glo_remainder_scheme_base;
extern object __glo_truncate_91quotient_scheme_base;
extern object __glo_truncate_91remainder_scheme_base;
extern object __glo_truncate_95_scheme_base;
extern object __glo_floor_91quotient_scheme_base;
extern object __glo_floor_91remainder_scheme_base;
extern object __glo_floor_95_scheme_base;
extern object __glo_square_scheme_base;
extern object __glo_expt_scheme_base;
extern object __glo_call_91with_91current_91continuation_scheme_base;
extern object __glo_call_95cc_scheme_base;
extern object __glo_call_91with_91values_scheme_base;
extern object __glo_dynamic_91wind_scheme_base;
extern object __glo_values_scheme_base;
extern object __glo_char_123_127_scheme_base;
extern object __glo_char_121_127_scheme_base;
extern object __glo_char_125_127_scheme_base;
extern object __glo_char_121_123_127_scheme_base;
extern object __glo_char_125_123_127_scheme_base;
extern object __glo_string_123_127_scheme_base;
extern object __glo_string_121_127_scheme_base;
extern object __glo_string_121_123_127_scheme_base;
extern object __glo_string_125_127_scheme_base;
extern object __glo_string_125_123_127_scheme_base;
extern object __glo_fast_91string_123_127_scheme_base;
extern object __glo_fast_91string_121_127_scheme_base;
extern object __glo_fast_91string_121_123_127_scheme_base;
extern object __glo_fast_91string_125_127_scheme_base;
extern object __glo_fast_91string_125_123_127_scheme_base;
extern object __glo_foldl_scheme_base;
extern object __glo_foldr_scheme_base;
extern object __glo_not_scheme_base;
extern object __glo_list_127_scheme_base;
extern object __glo_zero_127_scheme_base;
extern object __glo_positive_127_scheme_base;
extern object __glo_negative_127_scheme_base;
extern object __glo_append_scheme_base;
extern object __glo__list_scheme_base;
extern object __glo_make_91list_scheme_base;
extern object __glo_list_91copy_scheme_base;
extern object __glo_map_scheme_base;
extern object __glo_Cyc_91map_91loop_911_scheme_base;
extern object __glo_Cyc_91map_91loop_912_scheme_base;
extern object __glo_Cyc_91for_91each_91loop_911_scheme_base;
extern object __glo_Cyc_91for_91each_91loop_912_scheme_base;
extern object __glo_for_91each_scheme_base;
extern object __glo_list_91tail_scheme_base;
extern object __glo_list_91ref_scheme_base;
extern object __glo_list_91set_67_scheme_base;
extern object __glo_reverse_scheme_base;
extern object __glo_boolean_123_127_scheme_base;
extern object __glo_symbol_123_127_scheme_base;
extern object __glo_Cyc_91obj_123_127_scheme_base;
extern object __glo_vector_scheme_base;
extern object __glo_vector_91append_scheme_base;
extern object __glo_vector_91copy_scheme_base;
extern object __glo_vector_91copy_67_scheme_base;
extern object __glo_vector_91fill_67_scheme_base;
extern object __glo_vector_91_125list_scheme_base;
extern object __glo_vector_91_125string_scheme_base;
extern object __glo_vector_91map_scheme_base;
extern object __glo_vector_91for_91each_scheme_base;
extern object __glo_make_91string_scheme_base;
extern object __glo_string_scheme_base;
extern object __glo_string_91copy_scheme_base;
extern object __glo_string_91copy_67_scheme_base;
extern object __glo_string_91fill_67_scheme_base;
extern object __glo_string_91_125list_scheme_base;
extern object __glo_string_91_125vector_scheme_base;
extern object __glo_string_91map_scheme_base;
extern object __glo_string_91for_91each_scheme_base;
extern object __glo_make_91parameter_scheme_base;
extern object __glo_current_91output_91port_scheme_base;
extern object __glo_current_91input_91port_scheme_base;
extern object __glo_current_91error_91port_scheme_base;
extern object __glo_call_91with_91port_scheme_base;
extern object __glo_error_91object_127_scheme_base;
extern object __glo_error_91object_91message_scheme_base;
extern object __glo_error_91object_91irritants_scheme_base;
extern object __glo_error_95loc_scheme_base;
extern object __glo_error_scheme_base;
extern object __glo_raise_scheme_base;
extern object __glo_raise_91continuable_scheme_base;
extern object __glo_with_91handler_scheme_base;
extern object __glo_with_91exception_91handler_scheme_base;
extern object __glo_Cyc_91add_91exception_91handler_scheme_base;
extern object __glo_Cyc_91remove_91exception_91handler_scheme_base;
extern object __glo_newline_scheme_base;
extern object __glo_write_91char_scheme_base;
extern object __glo_write_91string_scheme_base;
extern object __glo_write_91string_911_scheme_base;
extern object __glo_write_91string_912_scheme_base;
extern object __glo_flush_91output_91port_scheme_base;
extern object __glo_peek_91char_scheme_base;
extern object __glo_read_91char_scheme_base;
extern object __glo_read_91line_scheme_base;
extern object __glo_read_91string_scheme_base;
extern object __glo_input_91port_127_scheme_base;
extern object __glo_output_91port_127_scheme_base;
extern object __glo_input_91port_91open_127_scheme_base;
extern object __glo_output_91port_91open_127_scheme_base;
extern object __glo_get_91output_91string_scheme_base;
extern object __glo_open_91output_91string_scheme_base;
extern object __glo_open_91input_91string_scheme_base;
extern object __glo_get_91output_91bytevector_scheme_base;
extern object __glo_open_91input_91bytevector_scheme_base;
extern object __glo_open_91output_91bytevector_scheme_base;
extern object __glo_features_scheme_base;
extern object __glo_Cyc_91add_91feature_67_scheme_base;
extern object __glo_Cyc_91version_scheme_base;
extern object __glo_any_scheme_base;
extern object __glo_every_scheme_base;
extern object __glo_and_scheme_base;
extern object __glo_or_scheme_base;
extern object __glo_let_scheme_base;
extern object __glo_let_85_scheme_base;
extern object __glo_letrec_scheme_base;
extern object __glo_let_85_91values_scheme_base;
extern object __glo_let_91values_scheme_base;
extern object __glo_define_91values_scheme_base;
extern object __glo_begin_scheme_base;
extern object __glo__case_scheme_base;
extern object __glo_cond_scheme_base;
extern object __glo_cond_91expand_scheme_base;
extern object __glo__do_scheme_base;
extern object __glo_when_scheme_base;
extern object __glo_unless_scheme_base;
extern object __glo_quasiquote_scheme_base;
extern object __glo_floor_scheme_base;
extern object __glo_ceiling_scheme_base;
extern object __glo_truncate_scheme_base;
extern object __glo_round_scheme_base;
extern object __glo_exact_scheme_base;
extern object __glo_inexact_scheme_base;
extern object __glo_eof_91object_scheme_base;
extern object __glo__void_scheme_base;
extern object __glo_syntax_91error_scheme_base;
extern object __glo_bytevector_91copy_scheme_base;
extern object __glo_bytevector_91copy_67_scheme_base;
extern object __glo_utf8_91_125string_scheme_base;
extern object __glo_string_91_125utf8_scheme_base;
extern object __glo_denominator_scheme_base;
extern object __glo_numerator_scheme_base;
extern object __glo_parameterize_scheme_base;
extern object __glo_read_91bytevector_scheme_base;
extern object __glo_read_91bytevector_67_scheme_base;
extern object __glo_write_91bytevector_scheme_base;
extern object __glo_peek_91u8_scheme_base;
extern object __glo_read_91u8_scheme_base;
extern object __glo_write_91u8_scheme_base;
extern object __glo_binary_91port_127_scheme_base;
extern object __glo_textual_91port_127_scheme_base;
extern object __glo_read_scheme_read;
extern object __glo_read_91all_scheme_read;
extern object __glo_read_91all_95source_scheme_read;
extern object __glo_include_scheme_read;
extern object __glo_include_91ci_scheme_read;
extern object __glo_display_scheme_write;
extern object __glo_write_scheme_write;
extern object __glo_call_91with_91input_91file_scheme_file;
extern object __glo_call_91with_91output_91file_scheme_file;
extern object __glo_with_91input_91from_91file_scheme_file;
extern object __glo_with_91output_91to_91file_scheme_file;
extern object __glo_format_srfi_28;
extern object __glo_match_91syntax_91error_cyclone_match;
extern object __glo_match_cyclone_match;
extern object __glo_match_91next_cyclone_match;
extern object __glo_match_91one_cyclone_match;
extern object __glo_match_91two_cyclone_match;
extern object __glo_match_91quasiquote_cyclone_match;
extern object __glo_match_91quasiquote_91step_cyclone_match;
extern object __glo_match_91drop_91ids_cyclone_match;
extern object __glo_match_91tuck_91ids_cyclone_match;
extern object __glo_match_91drop_91first_91arg_cyclone_match;
extern object __glo_match_91gen_91or_cyclone_match;
extern object __glo_match_91gen_91or_91step_cyclone_match;
extern object __glo_match_91gen_91ellipsis_cyclone_match;
extern object __glo_match_91verify_91no_91ellipsis_cyclone_match;
extern object __glo_match_91gen_91search_cyclone_match;
extern object __glo_match_91vector_cyclone_match;
extern object __glo_match_91vector_91two_cyclone_match;
extern object __glo_match_91vector_91step_cyclone_match;
extern object __glo_match_91gen_91vector_91ellipsis_cyclone_match;
extern object __glo_match_91vector_91tail_cyclone_match;
extern object __glo_match_91vector_91tail_91two_cyclone_match;
extern object __glo_match_91record_91refs_cyclone_match;
extern object __glo_match_91record_91named_91refs_cyclone_match;
extern object __glo_match_91extract_91vars_cyclone_match;
extern object __glo_match_91extract_91vars_91step_cyclone_match;
extern object __glo_match_91extract_91quasiquote_91vars_cyclone_match;
extern object __glo_match_91extract_91quasiquote_91vars_91step_cyclone_match;
extern object __glo_match_91lambda_cyclone_match;
extern object __glo_match_91lambda_85_cyclone_match;
extern object __glo_match_91let_cyclone_match;
extern object __glo_match_91letrec_cyclone_match;
extern object __glo_match_91let_95helper_cyclone_match;
extern object __glo_match_91named_91let_cyclone_match;
extern object __glo_match_91let_85_cyclone_match;
extern object __glo_match_91check_91identifier_cyclone_match;
extern object __glo_match_91check_91ellipsis_cyclone_match;
extern object __glo__85cyclone_91winds_91version_85_libs_common;
extern object __glo__85default_91code_91directory_85_libs_common;
extern object __glo__85default_91lock_91file_85_libs_common;
extern object __glo__85default_91doc_91url_85_libs_common;
extern object __glo__85default_91doc_91file_85_libs_common;
extern object __glo__85doc_91candidates_85_libs_common;
extern object __glo__85library_91installable_91extensions_85_libs_common;
extern object __glo_get_91library_91installation_91dir_libs_common;
extern object __glo_get_91program_91installation_91dir_libs_common;
extern object __glo_directory_91content_libs_file;
extern object __glo_path_91dir_libs_file;
extern object __glo_path_91strip_91directory_libs_file;
extern object __glo_path_91strip_91extension_libs_file;
extern object __glo_path_91extension_libs_file;
extern object __glo__91_125path_libs_file;
extern object __glo_random_91temp_91dir_libs_file;
extern object __glo_test_91file_127_libs_file;
extern object __glo_code_91files_libs_file;
extern object __glo_sld_91files_libs_file;
extern object __glo_scm_91files_libs_file;
extern object __glo_doc_91file_127_libs_file;
extern object __glo__85log_91level_85_libs_system_91calls;
extern object __glo_ok_127_libs_system_91calls;
extern object __glo_download_67_libs_system_91calls;
extern object __glo_validate_91sha256sum_libs_system_91calls;
extern object __glo_extract_67_libs_system_91calls;
extern object __glo_delete_67_libs_system_91calls;
extern object __glo_compile_67_libs_system_91calls;
extern object __glo_make_91dir_67_libs_system_91calls;
extern object __glo_copy_91file_91to_91dir_67_libs_system_91calls;
extern object __glo_copy_91dir_91to_91dir_67_libs_system_91calls;
extern object __glo_copy_91file_67_libs_system_91calls;
extern object __glo_touch_67_libs_system_91calls;
extern object __glo_remove_libs_util;
extern object __glo_get_91parameter_91value_libs_util;
extern object __glo_get_91parameter_91all_91occurrences_libs_util;
extern object __glo_trim_91trailing_91slash_libs_util;
extern object __glo__91_125string_libs_util;
extern object __glo_string_91join_libs_util;
extern object __glo_string_91find_91right_libs_util;
extern object __glo_string_91contains_libs_util;
extern object __glo_string_91_125proper_91symbol_libs_util;
extern object __glo_fast_91string_123_127_191_191inline_191_191_scheme_base;
extern object __glo_fast_91string_121_127_191_191inline_191_191_scheme_base;
extern object __glo_fast_91string_121_123_127_191_191inline_191_191_scheme_base;
extern object __glo_fast_91string_125_127_191_191inline_191_191_scheme_base;
extern object __glo_fast_91string_125_123_127_191_191inline_191_191_scheme_base;
extern object __glo__75write_91bytevector_191_191inline_191_191_scheme_base;
extern object __glo_not_191_191inline_191_191_scheme_base;
extern object __glo_list_127_191_191inline_191_191_scheme_base;
extern object __glo_zero_127_191_191inline_191_191_scheme_base;
extern object __glo_positive_127_191_191inline_191_191_scheme_base;
extern object __glo_negative_127_191_191inline_191_191_scheme_base;
extern object __glo_floor_191_191inline_191_191_scheme_base;
extern object __glo_ceiling_191_191inline_191_191_scheme_base;
extern object __glo_truncate_191_191inline_191_191_scheme_base;
extern object __glo_round_191_191inline_191_191_scheme_base;
extern object __glo_inexact_191_191inline_191_191_scheme_base;
extern object __glo_sqrt_191_191inline_191_191_scheme_base;
extern object __glo_exact_91integer_127_191_191inline_191_191_scheme_base;
extern object __glo_exact_127_191_191inline_191_191_scheme_base;
extern object __glo_complex_127_191_191inline_191_191_scheme_base;
extern object __glo_denominator_191_191inline_191_191_scheme_base;
extern object __glo_numerator_191_191inline_191_191_scheme_base;
extern object __glo_quotient_191_191inline_191_191_scheme_base;
extern object __glo_square_191_191inline_191_191_scheme_base;
extern object __glo_eof_91object_191_191inline_191_191_scheme_base;
extern object __glo_void_191_191inline_191_191_scheme_base;
extern object __glo_Cyc_91opaque_91eq_127_191_191inline_191_191_scheme_read;
extern object __glo_Cyc_91opaque_91unsafe_91eq_127_191_191inline_191_191_scheme_read;
extern object __glo_Cyc_91opaque_91unsafe_91string_127_191_191inline_191_191_scheme_read;
#include "cyclone/runtime.h"
defsymbol(_85default_91local_91index_85);
defsymbol(match);
static void __lambda_42(void *data, int argc, closure _,object k_734447) ;
static void __lambda_43(void *data, int argc, object self_734488, object r_734450) ;
static void __lambda_44(void *data, int argc, object self_734489, object r_734451) ;
static void __lambda_45(void *data, int argc, object self_734490, object r_734449) ;
static void __lambda_35(void *data, int argc, closure _,object k_734435, object name_734320_734359) ;
static void __lambda_36(void *data, int argc, object self_734482, object local_91index_734323_734360) ;
static void __lambda_39(void *data, int argc, object self_734485, object k_734440) ;
static void __lambda_41(void *data, int argc, object self_734487, object k_734443, object pkg_734325_734361) ;
static void __lambda_40(void *data, int argc, object self_734486, object r_734441) ;
static void __lambda_37(void *data, int argc, object self_734483, object r_734437) ;
static void __lambda_38(void *data, int argc, object self_734484, object r_734438) ;
static void __lambda_27(void *data, int argc, closure _,object k_734421, object name_734313_734352, object version_734314_734353, object cyc_91version_734315_734354, object libs_734316_734355, object progs_734317_734356) ;
static void __lambda_28(void *data, int argc, object self_734475, object local_91index_734318_734357) ;
static void __lambda_31(void *data, int argc, object self_734478, object k_734426) ;
static void __lambda_32(void *data, int argc, object self_734479, object r_734428) ;
static void __lambda_34(void *data, int argc, object self_734481, object k_734431, object pkg_734319_734358) ;
static void __lambda_33(void *data, int argc, object self_734480, object r_734429) ;
static void __lambda_29(void *data, int argc, object self_734476, object r_734423) ;
static void __lambda_30(void *data, int argc, object self_734477, object r_734424) ;
static void __lambda_26(void *data, int argc, closure _,object k_734416) ;
static void __lambda_17(void *data, int argc, closure _,object k_734399, object index_734293_734341, object name_734294_734342, object pkg_91ver_734295_734343, object cyc_91ver_734296_734344) ;
static void __lambda_18(void *data, int argc, object self_734466, object _91_125num_734346) ;
static void __lambda_46(void *data, int argc, object self_734467, object _91_125num_734346) ;
static void __lambda_25(void *data, int argc, object self_734468, object k_734411, object obj_734297_734348) ;
static void __lambda_19(void *data, int argc, object self_734469, object r_734400) ;
static void __lambda_20(void *data, int argc, object self_734470, object metadata_734305_734349) ;
static void __lambda_21(void *data, int argc, object self_734471, object r_734408) ;
static void __lambda_22(void *data, int argc, object self_734472, object r_734409) ;
static void __lambda_23(void *data, int argc, object self_734473, object r_734406) ;
static void __lambda_24(void *data, int argc, object self_734474, object r_734407) ;
static void __lambda_11(void *data, int argc, closure _,object k_734379, object index_739_734329, object pkg_91name_7310_734330) ;
static void __lambda_12(void *data, int argc, object self_734461, object v_7386_7388_734331) ;
static void __lambda_14(void *data, int argc, object self_734463, object k_734384) ;
static void __lambda_16(void *data, int argc, object self_734464, object k_734393) ;
static void __lambda_15(void *data, int argc, object self_734465, object failure_73892_73946_734333) ;
static void __lambda_13(void *data, int argc, object self_734462, object r_734383) ;
static void __lambda_1(void *data, int argc, closure _,object k_734366) ;
static void __lambda_2(void *data, int argc, object self_734452, object tmp_91dir_733_734326) ;
static void __lambda_3(void *data, int argc, object self_734453, object index_91path_736_734327) ;
static void __lambda_4(void *data, int argc, object self_734454, object r_734369) ;
static void __lambda_5(void *data, int argc, object self_734455, object r_734376) ;
static void __lambda_6(void *data, int argc, object self_734456, object r_734370) ;
static void __lambda_7(void *data, int argc, object self_734457, object r_734371) ;
static void __lambda_8(void *data, int argc, object self_734458, object r_734375) ;
static void __lambda_9(void *data, int argc, object self_734459, object r_734374) ;
static void __lambda_10(void *data, int argc, object self_734460, object r_734373) ;

static void __lambda_42(void *data, int argc, closure _,object k_734447) {
  Cyc_st_add(data, "libs/index.sld:lib-init:libsindex");

closureN_type c_734755;
object e_734769 [1];
c_734755.hdr.mark = gc_color_red;
 c_734755.hdr.grayed = 0;
c_734755.tag = closureN_tag;
 c_734755.fn = (function_type)__lambda_43;
c_734755.num_args = 1;
c_734755.num_elements = 1;
c_734755.elements = (object *)e_734769;
c_734755.elements[0] = k_734447;

return_closcall1(data,  __glo_get_91library_91installation_91dir_libs_common,  &c_734755);; 
}

static void __lambda_43(void *data, int argc, object self_734488, object r_734450) {
  
closureN_type c_734757;
object e_734768 [2];
c_734757.hdr.mark = gc_color_red;
 c_734757.hdr.grayed = 0;
c_734757.tag = closureN_tag;
 c_734757.fn = (function_type)__lambda_44;
c_734757.num_args = 1;
c_734757.num_elements = 2;
c_734757.elements = (object *)e_734768;
c_734757.elements[0] = ((closureN)self_734488)->elements[0];
c_734757.elements[1] = r_734450;

return_closcall1(data,  __glo__85default_91code_91directory_85_libs_common,  &c_734757);; 
}

static void __lambda_44(void *data, int argc, object self_734489, object r_734451) {
  
closureN_type c_734759;
object e_734765 [1];
c_734759.hdr.mark = gc_color_red;
 c_734759.hdr.grayed = 0;
c_734759.tag = closureN_tag;
 c_734759.fn = (function_type)__lambda_45;
c_734759.num_args = 1;
c_734759.num_elements = 1;
c_734759.elements = (object *)e_734765;
c_734759.elements[0] = ((closureN)self_734489)->elements[0];


make_utf8_string_with_len(c_734767, "cyclone-winds-index.scm", 23, 23);
return_closcall4(data,  __glo__91_125path_libs_file,  &c_734759, ((closureN)self_734489)->elements[1], r_734451, &c_734767);; 
}

static void __lambda_45(void *data, int argc, object self_734490, object r_734449) {
  
object c_734764 = global_set_cps_id(data,  ((closureN)self_734490)->elements[0],"__glo__85default_91local_91index_85_libs_index", __glo__85default_91local_91index_85_libs_index, r_734449);
return_closcall1(data,  ((closureN)self_734490)->elements[0],  c_734764);; 
}

static void __lambda_35(void *data, int argc, closure _,object k_734435, object name_734320_734359) {
  Cyc_st_add(data, "libs/index.sld:unregister-installed-package!");

closureN_type c_734725;
object e_734752 [2];
c_734725.hdr.mark = gc_color_red;
 c_734725.hdr.grayed = 0;
c_734725.tag = closureN_tag;
 c_734725.fn = (function_type)__lambda_36;
c_734725.num_args = 1;
c_734725.num_elements = 2;
c_734725.elements = (object *)e_734752;
c_734725.elements[0] = k_734435;
c_734725.elements[1] = name_734320_734359;

return_closcall1(data,  __glo_get_91local_91index_libs_index,  &c_734725);; 
}

static void __lambda_36(void *data, int argc, object self_734482, object local_91index_734323_734360) {
  
closureN_type c_734727;
object e_734735 [2];
c_734727.hdr.mark = gc_color_red;
 c_734727.hdr.grayed = 0;
c_734727.tag = closureN_tag;
 c_734727.fn = (function_type)__lambda_37;
c_734727.num_args = 1;
c_734727.num_elements = 2;
c_734727.elements = (object *)e_734735;
c_734727.elements[0] = ((closureN)self_734482)->elements[0];
c_734727.elements[1] = ((closureN)self_734482)->elements[1];


closureN_type c_734736;
object e_734751 [2];
c_734736.hdr.mark = gc_color_red;
 c_734736.hdr.grayed = 0;
c_734736.tag = closureN_tag;
 c_734736.fn = (function_type)__lambda_39;
c_734736.num_args = 0;
c_734736.num_elements = 2;
c_734736.elements = (object *)e_734751;
c_734736.elements[0] = local_91index_734323_734360;
c_734736.elements[1] = ((closureN)self_734482)->elements[1];

return_closcall3(data,  __glo_with_91output_91to_91file_scheme_file,  &c_734727, __glo__85default_91local_91index_85_libs_index, &c_734736);; 
}

static void __lambda_39(void *data, int argc, object self_734485, object k_734440) {
  
closureN_type c_734738;
object e_734741 [1];
c_734738.hdr.mark = gc_color_red;
 c_734738.hdr.grayed = 0;
c_734738.tag = closureN_tag;
 c_734738.fn = (function_type)__lambda_40;
c_734738.num_args = 1;
c_734738.num_elements = 1;
c_734738.elements = (object *)e_734741;
c_734738.elements[0] = k_734440;


closureN_type c_734742;
object e_734749 [1];
c_734742.hdr.mark = gc_color_red;
 c_734742.hdr.grayed = 0;
c_734742.tag = closureN_tag;
 c_734742.fn = (function_type)__lambda_41;
c_734742.num_args = 1;
c_734742.num_elements = 1;
c_734742.elements = (object *)e_734749;
c_734742.elements[0] = ((closureN)self_734485)->elements[1];

return_closcall3(data,  __glo_remove_libs_util,  &c_734738, &c_734742, ((closureN)self_734485)->elements[0]);; 
}

static void __lambda_41(void *data, int argc, object self_734487, object k_734443, object pkg_734325_734361) {
  



return_closcall1(data,  k_734443,  equalp(Cyc_car(data, pkg_734325_734361), ((closureN)self_734487)->elements[0]));; 
}

static void __lambda_40(void *data, int argc, object self_734486, object r_734441) {
  return_closcall2(data,  __glo_write_scheme_write,  ((closureN)self_734486)->elements[0], r_734441);; 
}

static void __lambda_37(void *data, int argc, object self_734483, object r_734437) {
  
closureN_type c_734729;
object e_734732 [1];
c_734729.hdr.mark = gc_color_red;
 c_734729.hdr.grayed = 0;
c_734729.tag = closureN_tag;
 c_734729.fn = (function_type)__lambda_38;
c_734729.num_args = 1;
c_734729.num_elements = 1;
c_734729.elements = (object *)e_734732;
c_734729.elements[0] = ((closureN)self_734483)->elements[0];


make_utf8_string_with_len(c_734733, "Package ~a successfuly uninstalled.~%", 37, 37);
return_closcall3(data,  __glo_format_srfi_28,  &c_734729, &c_734733, ((closureN)self_734483)->elements[1]);; 
}

static void __lambda_38(void *data, int argc, object self_734484, object r_734438) {
  return_closcall2(data,  __glo_display_scheme_write,  ((closureN)self_734484)->elements[0], r_734438);; 
}

static void __lambda_27(void *data, int argc, closure _,object k_734421, object name_734313_734352, object version_734314_734353, object cyc_91version_734315_734354, object libs_734316_734355, object progs_734317_734356) {
  Cyc_st_add(data, "libs/index.sld:register-installed-package!");

closureN_type c_734681;
object e_734722 [6];
c_734681.hdr.mark = gc_color_red;
 c_734681.hdr.grayed = 0;
c_734681.tag = closureN_tag;
 c_734681.fn = (function_type)__lambda_28;
c_734681.num_args = 1;
c_734681.num_elements = 6;
c_734681.elements = (object *)e_734722;
c_734681.elements[0] = cyc_91version_734315_734354;
c_734681.elements[1] = k_734421;
c_734681.elements[2] = libs_734316_734355;
c_734681.elements[3] = name_734313_734352;
c_734681.elements[4] = progs_734317_734356;
c_734681.elements[5] = version_734314_734353;

return_closcall1(data,  __glo_get_91local_91index_libs_index,  &c_734681);; 
}

static void __lambda_28(void *data, int argc, object self_734475, object local_91index_734318_734357) {
  
closureN_type c_734683;
object e_734693 [4];
c_734683.hdr.mark = gc_color_red;
 c_734683.hdr.grayed = 0;
c_734683.tag = closureN_tag;
 c_734683.fn = (function_type)__lambda_29;
c_734683.num_args = 1;
c_734683.num_elements = 4;
c_734683.elements = (object *)e_734693;
c_734683.elements[0] = ((closureN)self_734475)->elements[0];
c_734683.elements[1] = ((closureN)self_734475)->elements[1];
c_734683.elements[2] = ((closureN)self_734475)->elements[3];
c_734683.elements[3] = ((closureN)self_734475)->elements[5];


closureN_type c_734694;
object e_734721 [6];
c_734694.hdr.mark = gc_color_red;
 c_734694.hdr.grayed = 0;
c_734694.tag = closureN_tag;
 c_734694.fn = (function_type)__lambda_31;
c_734694.num_args = 0;
c_734694.num_elements = 6;
c_734694.elements = (object *)e_734721;
c_734694.elements[0] = ((closureN)self_734475)->elements[0];
c_734694.elements[1] = ((closureN)self_734475)->elements[2];
c_734694.elements[2] = local_91index_734318_734357;
c_734694.elements[3] = ((closureN)self_734475)->elements[3];
c_734694.elements[4] = ((closureN)self_734475)->elements[4];
c_734694.elements[5] = ((closureN)self_734475)->elements[5];

return_closcall3(data,  __glo_with_91output_91to_91file_scheme_file,  &c_734683, __glo__85default_91local_91index_85_libs_index, &c_734694);; 
}

static void __lambda_31(void *data, int argc, object self_734478, object k_734426) {
  
closureN_type c_734696;
object e_734715 [3];
c_734696.hdr.mark = gc_color_red;
 c_734696.hdr.grayed = 0;
c_734696.tag = closureN_tag;
 c_734696.fn = (function_type)__lambda_32;
c_734696.num_args = 1;
c_734696.num_elements = 3;
c_734696.elements = (object *)e_734715;
c_734696.elements[0] = k_734426;
c_734696.elements[1] = ((closureN)self_734478)->elements[2];
c_734696.elements[2] = ((closureN)self_734478)->elements[3];

return_closcall6(data,  __glo__list_scheme_base,  &c_734696, ((closureN)self_734478)->elements[3], ((closureN)self_734478)->elements[5], ((closureN)self_734478)->elements[0], ((closureN)self_734478)->elements[1], ((closureN)self_734478)->elements[4]);; 
}

static void __lambda_32(void *data, int argc, object self_734479, object r_734428) {
  
closureN_type c_734698;
object e_734705 [2];
c_734698.hdr.mark = gc_color_red;
 c_734698.hdr.grayed = 0;
c_734698.tag = closureN_tag;
 c_734698.fn = (function_type)__lambda_33;
c_734698.num_args = 1;
c_734698.num_elements = 2;
c_734698.elements = (object *)e_734705;
c_734698.elements[0] = ((closureN)self_734479)->elements[0];
c_734698.elements[1] = r_734428;


closureN_type c_734706;
object e_734713 [1];
c_734706.hdr.mark = gc_color_red;
 c_734706.hdr.grayed = 0;
c_734706.tag = closureN_tag;
 c_734706.fn = (function_type)__lambda_34;
c_734706.num_args = 1;
c_734706.num_elements = 1;
c_734706.elements = (object *)e_734713;
c_734706.elements[0] = ((closureN)self_734479)->elements[2];

return_closcall3(data,  __glo_remove_libs_util,  &c_734698, &c_734706, ((closureN)self_734479)->elements[1]);; 
}

static void __lambda_34(void *data, int argc, object self_734481, object k_734431, object pkg_734319_734358) {
  



return_closcall1(data,  k_734431,  equalp(Cyc_car(data, pkg_734319_734358), ((closureN)self_734481)->elements[0]));; 
}

static void __lambda_33(void *data, int argc, object self_734480, object r_734429) {
  
pair_type local_734703; 
return_closcall2(data,  __glo_write_scheme_write,  ((closureN)self_734480)->elements[0], set_pair_as_expr(&local_734703, ((closureN)self_734480)->elements[1], r_734429));; 
}

static void __lambda_29(void *data, int argc, object self_734476, object r_734423) {
  
closureN_type c_734685;
object e_734688 [1];
c_734685.hdr.mark = gc_color_red;
 c_734685.hdr.grayed = 0;
c_734685.tag = closureN_tag;
 c_734685.fn = (function_type)__lambda_30;
c_734685.num_args = 1;
c_734685.num_elements = 1;
c_734685.elements = (object *)e_734688;
c_734685.elements[0] = ((closureN)self_734476)->elements[1];


make_utf8_string_with_len(c_734689, "Package ~a ~a successfuly installed with Cyclone ~a.~%", 54, 54);
return_closcall5(data,  __glo_format_srfi_28,  &c_734685, &c_734689, ((closureN)self_734476)->elements[2], ((closureN)self_734476)->elements[3], ((closureN)self_734476)->elements[0]);; 
}

static void __lambda_30(void *data, int argc, object self_734477, object r_734424) {
  return_closcall2(data,  __glo_display_scheme_write,  ((closureN)self_734477)->elements[0], r_734424);; 
}

static void __lambda_26(void *data, int argc, closure _,object k_734416) {
  Cyc_st_add(data, "libs/index.sld:get-local-index");
  
if( (boolean_f != Cyc_io_file_exists(data, __glo__85default_91local_91index_85_libs_index)) ){ 
  
port_type c_734677 = Cyc_io_open_input_file(data,__glo__85default_91local_91index_85_libs_index);
return_closcall2(data,  __glo_read_scheme_read,  k_734416, &c_734677);
} else { 
  return_closcall1(data,  k_734416,  NULL);}
;; 
}

static void __lambda_17(void *data, int argc, closure _,object k_734399, object index_734293_734341, object name_734294_734342, object pkg_91ver_734295_734343, object cyc_91ver_734296_734344) {
  Cyc_st_add(data, "libs/index.sld:local-index-contains?");

closureN_type c_734594;
object e_734670 [5];
c_734594.hdr.mark = gc_color_red;
 c_734594.hdr.grayed = 0;
c_734594.tag = closureN_tag;
 c_734594.fn = (function_type)__lambda_18;
c_734594.num_args = 1;
c_734594.num_elements = 5;
c_734594.elements = (object *)e_734670;
c_734594.elements[0] = cyc_91ver_734296_734344;
c_734594.elements[1] = index_734293_734341;
c_734594.elements[2] = k_734399;
c_734594.elements[3] = name_734294_734342;
c_734594.elements[4] = pkg_91ver_734295_734343;

return_direct_with_clo1(data,(closure)&c_734594,__lambda_18,  boolean_f);; 
}

static void __lambda_18(void *data, int argc, object self_734466, object _91_125num_734346) {
  
closureN_type c_734596;
object e_734666 [5];
c_734596.hdr.mark = gc_color_red;
 c_734596.hdr.grayed = 0;
c_734596.tag = closureN_tag;
 c_734596.fn = (function_type)__lambda_46;
c_734596.num_args = 1;
c_734596.num_elements = 5;
c_734596.elements = (object *)e_734666;
c_734596.elements[0] = ((closureN)self_734466)->elements[0];
c_734596.elements[1] = ((closureN)self_734466)->elements[1];
c_734596.elements[2] = ((closureN)self_734466)->elements[2];
c_734596.elements[3] = ((closureN)self_734466)->elements[3];
c_734596.elements[4] = ((closureN)self_734466)->elements[4];


pair_type local_734669; 
return_direct_with_clo1(data,(closure)&c_734596,__lambda_46,  set_cell_as_expr(&local_734669, _91_125num_734346));; 
}

static void __lambda_46(void *data, int argc, object self_734467, object _91_125num_734346) {
  
closureN_type c_734598;
object e_734651 [6];
c_734598.hdr.mark = gc_color_red;
 c_734598.hdr.grayed = 0;
c_734598.tag = closureN_tag;
 c_734598.fn = (function_type)__lambda_19;
c_734598.num_args = 1;
c_734598.num_elements = 6;
c_734598.elements = (object *)e_734651;
c_734598.elements[0] = _91_125num_734346;
c_734598.elements[1] = ((closureN)self_734467)->elements[0];
c_734598.elements[2] = ((closureN)self_734467)->elements[1];
c_734598.elements[3] = ((closureN)self_734467)->elements[2];
c_734598.elements[4] = ((closureN)self_734467)->elements[3];
c_734598.elements[5] = ((closureN)self_734467)->elements[4];




mclosure0(c_734654, (function_type)__lambda_25);c_734654.num_args = 1;
return_direct_with_clo1(data,(closure)&c_734598,__lambda_19,  Cyc_set_cell(data, _91_125num_734346, &c_734654));; 
}

static void __lambda_25(void *data, int argc, object self_734468, object k_734411, object obj_734297_734348) {
    
if( (boolean_f != Cyc_is_string(obj_734297_734348)) ){ 
  
object c_734660 = Cyc_string2number2_(data,  k_734411,1,obj_734297_734348);
return_closcall1(data,  k_734411,  c_734660);
} else { 
    
if( (boolean_f != Cyc_is_number(obj_734297_734348)) ){ 
  return_closcall1(data,  k_734411,  obj_734297_734348);
} else { 
  
make_utf8_string_with_len(c_734665, "Unable to convert to number", 27, 27);
return_closcall3(data,  __glo_error_scheme_base,  k_734411, &c_734665, obj_734297_734348);}
;}
;; 
}

static void __lambda_19(void *data, int argc, object self_734469, object r_734400) {
  
closureN_type c_734600;
object e_734646 [4];
c_734600.hdr.mark = gc_color_red;
 c_734600.hdr.grayed = 0;
c_734600.tag = closureN_tag;
 c_734600.fn = (function_type)__lambda_20;
c_734600.num_args = 1;
c_734600.num_elements = 4;
c_734600.elements = (object *)e_734646;
c_734600.elements[0] = ((closureN)self_734469)->elements[0];
c_734600.elements[1] = ((closureN)self_734469)->elements[1];
c_734600.elements[2] = ((closureN)self_734469)->elements[3];
c_734600.elements[3] = ((closureN)self_734469)->elements[5];



return_direct_with_clo1(data,(closure)&c_734600,__lambda_20,  assoc(data, ((closureN)self_734469)->elements[4], ((closureN)self_734469)->elements[2]));; 
}

static void __lambda_20(void *data, int argc, object self_734470, object metadata_734305_734349) {
    
if( (boolean_f != Cyc_is_pair(metadata_734305_734349)) ){ 
  


closureN_type c_734607;
object e_734641 [5];
c_734607.hdr.mark = gc_color_red;
 c_734607.hdr.grayed = 0;
c_734607.tag = closureN_tag;
 c_734607.fn = (function_type)__lambda_21;
c_734607.num_args = 1;
c_734607.num_elements = 5;
c_734607.elements = (object *)e_734641;
c_734607.elements[0] = ((closureN)self_734470)->elements[0];
c_734607.elements[1] = ((closureN)self_734470)->elements[1];
c_734607.elements[2] = ((closureN)self_734470)->elements[2];
c_734607.elements[3] = metadata_734305_734349;
c_734607.elements[4] = ((closureN)self_734470)->elements[3];



return_closcall2(data,  car(((closureN)self_734470)->elements[0]),  &c_734607, Cyc_cadr(data, metadata_734305_734349));
} else { 
  return_closcall1(data,  ((closureN)self_734470)->elements[2],  boolean_f);}
;; 
}

static void __lambda_21(void *data, int argc, object self_734471, object r_734408) {
  


closureN_type c_734612;
object e_734639 [5];
c_734612.hdr.mark = gc_color_red;
 c_734612.hdr.grayed = 0;
c_734612.tag = closureN_tag;
 c_734612.fn = (function_type)__lambda_22;
c_734612.num_args = 1;
c_734612.num_elements = 5;
c_734612.elements = (object *)e_734639;
c_734612.elements[0] = ((closureN)self_734471)->elements[0];
c_734612.elements[1] = ((closureN)self_734471)->elements[1];
c_734612.elements[2] = ((closureN)self_734471)->elements[2];
c_734612.elements[3] = ((closureN)self_734471)->elements[3];
c_734612.elements[4] = r_734408;

return_closcall2(data,  car(((closureN)self_734471)->elements[0]),  &c_734612, ((closureN)self_734471)->elements[4]);; 
}

static void __lambda_22(void *data, int argc, object self_734472, object r_734409) {
    
if( (boolean_f != Cyc_num_fast_gte_op(data, ((closureN)self_734472)->elements[4], r_734409)) ){ 
  


closureN_type c_734620;
object e_734633 [3];
c_734620.hdr.mark = gc_color_red;
 c_734620.hdr.grayed = 0;
c_734620.tag = closureN_tag;
 c_734620.fn = (function_type)__lambda_23;
c_734620.num_args = 1;
c_734620.num_elements = 3;
c_734620.elements = (object *)e_734633;
c_734620.elements[0] = ((closureN)self_734472)->elements[0];
c_734620.elements[1] = ((closureN)self_734472)->elements[1];
c_734620.elements[2] = ((closureN)self_734472)->elements[2];



return_closcall2(data,  car(((closureN)self_734472)->elements[0]),  &c_734620, Cyc_caddr(data, ((closureN)self_734472)->elements[3]));
} else { 
  return_closcall1(data,  ((closureN)self_734472)->elements[2],  boolean_f);}
;; 
}

static void __lambda_23(void *data, int argc, object self_734473, object r_734406) {
  


closureN_type c_734625;
object e_734631 [2];
c_734625.hdr.mark = gc_color_red;
 c_734625.hdr.grayed = 0;
c_734625.tag = closureN_tag;
 c_734625.fn = (function_type)__lambda_24;
c_734625.num_args = 1;
c_734625.num_elements = 2;
c_734625.elements = (object *)e_734631;
c_734625.elements[0] = ((closureN)self_734473)->elements[2];
c_734625.elements[1] = r_734406;

return_closcall2(data,  car(((closureN)self_734473)->elements[0]),  &c_734625, ((closureN)self_734473)->elements[1]);; 
}

static void __lambda_24(void *data, int argc, object self_734474, object r_734407) {
  

return_closcall1(data,  ((closureN)self_734474)->elements[0],  Cyc_num_fast_gte_op(data, ((closureN)self_734474)->elements[1], r_734407));; 
}

static void __lambda_11(void *data, int argc, closure _,object k_734379, object index_739_734329, object pkg_91name_7310_734330) {
  Cyc_st_add(data, "libs/index.sld:pkg-info");

closureN_type c_734536;
object e_734589 [2];
c_734536.hdr.mark = gc_color_red;
 c_734536.hdr.grayed = 0;
c_734536.tag = closureN_tag;
 c_734536.fn = (function_type)__lambda_12;
c_734536.num_args = 1;
c_734536.num_elements = 2;
c_734536.elements = (object *)e_734589;
c_734536.elements[0] = k_734379;
c_734536.elements[1] = pkg_91name_7310_734330;



return_direct_with_clo1(data,(closure)&c_734536,__lambda_12,  assoc(data, pkg_91name_7310_734330, index_739_734329));; 
}

static void __lambda_12(void *data, int argc, object self_734461, object v_7386_7388_734331) {
    
if( (boolean_f != equalp(v_7386_7388_734331, boolean_f)) ){ 
  
closureN_type c_734540;
object e_734543 [1];
c_734540.hdr.mark = gc_color_red;
 c_734540.hdr.grayed = 0;
c_734540.tag = closureN_tag;
 c_734540.fn = (function_type)__lambda_13;
c_734540.num_args = 1;
c_734540.num_elements = 1;
c_734540.elements = (object *)e_734543;
c_734540.elements[0] = ((closureN)self_734461)->elements[0];


make_utf8_string_with_len(c_734544, "Could not locate package by name: ~s~%", 38, 38);
return_closcall3(data,  __glo_format_srfi_28,  &c_734540, &c_734544, ((closureN)self_734461)->elements[1]);
} else { 
  
closureN_type c_734547;
object e_734587 [1];
c_734547.hdr.mark = gc_color_red;
 c_734547.hdr.grayed = 0;
c_734547.tag = closureN_tag;
 c_734547.fn = (function_type)__lambda_14;
c_734547.num_args = 0;
c_734547.num_elements = 1;
c_734547.elements = (object *)e_734587;
c_734547.elements[0] = v_7386_7388_734331;

return_direct_with_clo1(data,(closure)&c_734547,__lambda_14,  ((closureN)self_734461)->elements[0]);}
;; 
}

static void __lambda_14(void *data, int argc, object self_734463, object k_734384) {
  
closureN_type c_734549;
object e_734583 [2];
c_734549.hdr.mark = gc_color_red;
 c_734549.hdr.grayed = 0;
c_734549.tag = closureN_tag;
 c_734549.fn = (function_type)__lambda_15;
c_734549.num_args = 1;
c_734549.num_elements = 2;
c_734549.elements = (object *)e_734583;
c_734549.elements[0] = k_734384;
c_734549.elements[1] = ((closureN)self_734463)->elements[0];


mclosure0(c_734584, (function_type)__lambda_16);c_734584.num_args = 0;
return_direct_with_clo1(data,(closure)&c_734549,__lambda_15,  &c_734584);; 
}

static void __lambda_16(void *data, int argc, object self_734464, object k_734393) {
  
make_utf8_string_with_len(c_734586, "no matching pattern", 19, 19);
return_closcall3(data,  __glo_error_scheme_base,  k_734393, quote_match, &c_734586);; 
}

static void __lambda_15(void *data, int argc, object self_734465, object failure_73892_73946_734333) {
    
if( (boolean_f != Cyc_is_pair(((closureN)self_734465)->elements[1])) ){ 
  
  Cyc_car(data, ((closureN)self_734465)->elements[1]);  
  
if( (boolean_f != Cyc_is_pair(Cyc_cdr(data, ((closureN)self_734465)->elements[1]))) ){ 
    complex_num_type local_734561; 
  
  
if( (boolean_f != ((inline_function_type)
                   ((closure)__glo_list_127_191_191inline_191_191_scheme_base)->fn)(data,&local_734561, Cyc_cdr(data, Cyc_cdr(data, ((closureN)self_734465)->elements[1])))) ){ 
  



return_closcall1(data,  ((closureN)self_734465)->elements[0],  Cyc_car(data, Cyc_cdr(data, ((closureN)self_734465)->elements[1])));
} else { 
  return_direct_with_clo1(data,  failure_73892_73946_734333,__lambda_16,  ((closureN)self_734465)->elements[0]);}
;
} else { 
  return_direct_with_clo1(data,  failure_73892_73946_734333,__lambda_16,  ((closureN)self_734465)->elements[0]);}
;
} else { 
  return_direct_with_clo1(data,  failure_73892_73946_734333,__lambda_16,  ((closureN)self_734465)->elements[0]);}
;; 
}

static void __lambda_13(void *data, int argc, object self_734462, object r_734383) {
  return_closcall2(data,  __glo_error_scheme_base,  ((closureN)self_734462)->elements[0], r_734383);; 
}

static void __lambda_1(void *data, int argc, closure _,object k_734366) {
  Cyc_st_add(data, "libs/index.sld:get-index");

closureN_type c_734494;
object e_734533 [1];
c_734494.hdr.mark = gc_color_red;
 c_734494.hdr.grayed = 0;
c_734494.tag = closureN_tag;
 c_734494.fn = (function_type)__lambda_2;
c_734494.num_args = 1;
c_734494.num_elements = 1;
c_734494.elements = (object *)e_734533;
c_734494.elements[0] = k_734366;

return_closcall1(data,  __glo_random_91temp_91dir_libs_file,  &c_734494);; 
}

static void __lambda_2(void *data, int argc, object self_734452, object tmp_91dir_733_734326) {
  
closureN_type c_734496;
object e_734531 [2];
c_734496.hdr.mark = gc_color_red;
 c_734496.hdr.grayed = 0;
c_734496.tag = closureN_tag;
 c_734496.fn = (function_type)__lambda_3;
c_734496.num_args = 1;
c_734496.num_elements = 2;
c_734496.elements = (object *)e_734531;
c_734496.elements[0] = ((closureN)self_734452)->elements[0];
c_734496.elements[1] = tmp_91dir_733_734326;


make_utf8_string_with_len(c_734532, "index.scm", 9, 9);
return_closcall3(data,  __glo__91_125path_libs_file,  &c_734496, tmp_91dir_733_734326, &c_734532);; 
}

static void __lambda_3(void *data, int argc, object self_734453, object index_91path_736_734327) {
  
closureN_type c_734498;
object e_734529 [3];
c_734498.hdr.mark = gc_color_red;
 c_734498.hdr.grayed = 0;
c_734498.tag = closureN_tag;
 c_734498.fn = (function_type)__lambda_4;
c_734498.num_args = 1;
c_734498.num_elements = 3;
c_734498.elements = (object *)e_734529;
c_734498.elements[0] = index_91path_736_734327;
c_734498.elements[1] = ((closureN)self_734453)->elements[0];
c_734498.elements[2] = ((closureN)self_734453)->elements[1];

return_closcall2(data,  __glo_make_91dir_67_libs_system_91calls,  &c_734498, ((closureN)self_734453)->elements[1]);; 
}

static void __lambda_4(void *data, int argc, object self_734454, object r_734369) {
  
closureN_type c_734500;
object e_734527 [3];
c_734500.hdr.mark = gc_color_red;
 c_734500.hdr.grayed = 0;
c_734500.tag = closureN_tag;
 c_734500.fn = (function_type)__lambda_5;
c_734500.num_args = 1;
c_734500.num_elements = 3;
c_734500.elements = (object *)e_734527;
c_734500.elements[0] = ((closureN)self_734454)->elements[0];
c_734500.elements[1] = ((closureN)self_734454)->elements[1];
c_734500.elements[2] = ((closureN)self_734454)->elements[2];


make_utf8_string_with_len(c_734528, "Retrieving index file...~%", 26, 26);
return_closcall2(data,  __glo_format_srfi_28,  &c_734500, &c_734528);; 
}

static void __lambda_5(void *data, int argc, object self_734455, object r_734376) {
  
closureN_type c_734502;
object e_734526 [3];
c_734502.hdr.mark = gc_color_red;
 c_734502.hdr.grayed = 0;
c_734502.tag = closureN_tag;
 c_734502.fn = (function_type)__lambda_6;
c_734502.num_args = 1;
c_734502.num_elements = 3;
c_734502.elements = (object *)e_734526;
c_734502.elements[0] = ((closureN)self_734455)->elements[0];
c_734502.elements[1] = ((closureN)self_734455)->elements[1];
c_734502.elements[2] = ((closureN)self_734455)->elements[2];

return_closcall2(data,  __glo_display_scheme_write,  &c_734502, r_734376);; 
}

static void __lambda_6(void *data, int argc, object self_734456, object r_734370) {
  
closureN_type c_734504;
object e_734524 [3];
c_734504.hdr.mark = gc_color_red;
 c_734504.hdr.grayed = 0;
c_734504.tag = closureN_tag;
 c_734504.fn = (function_type)__lambda_7;
c_734504.num_args = 1;
c_734504.num_elements = 3;
c_734504.elements = (object *)e_734524;
c_734504.elements[0] = ((closureN)self_734456)->elements[0];
c_734504.elements[1] = ((closureN)self_734456)->elements[1];
c_734504.elements[2] = ((closureN)self_734456)->elements[2];

return_closcall3(data,  __glo_download_67_libs_system_91calls,  &c_734504, __glo__85default_91index_91url_85_libs_index, ((closureN)self_734456)->elements[0]);; 
}

static void __lambda_7(void *data, int argc, object self_734457, object r_734371) {
  
closureN_type c_734506;
object e_734519 [2];
c_734506.hdr.mark = gc_color_red;
 c_734506.hdr.grayed = 0;
c_734506.tag = closureN_tag;
 c_734506.fn = (function_type)__lambda_8;
c_734506.num_args = 1;
c_734506.num_elements = 2;
c_734506.elements = (object *)e_734519;
c_734506.elements[0] = ((closureN)self_734457)->elements[1];
c_734506.elements[1] = ((closureN)self_734457)->elements[2];


port_type c_734522 = Cyc_io_open_input_file(data,((closureN)self_734457)->elements[0]);
return_direct_with_clo1(data,(closure)&c_734506,__lambda_8,  &c_734522);; 
}

static void __lambda_8(void *data, int argc, object self_734458, object r_734375) {
  
closureN_type c_734508;
object e_734518 [2];
c_734508.hdr.mark = gc_color_red;
 c_734508.hdr.grayed = 0;
c_734508.tag = closureN_tag;
 c_734508.fn = (function_type)__lambda_9;
c_734508.num_args = 1;
c_734508.num_elements = 2;
c_734508.elements = (object *)e_734518;
c_734508.elements[0] = ((closureN)self_734458)->elements[0];
c_734508.elements[1] = ((closureN)self_734458)->elements[1];

return_closcall2(data,  __glo_read_scheme_read,  &c_734508, r_734375);; 
}

static void __lambda_9(void *data, int argc, object self_734459, object r_734374) {
  
closureN_type c_734510;
object e_734516 [2];
c_734510.hdr.mark = gc_color_red;
 c_734510.hdr.grayed = 0;
c_734510.tag = closureN_tag;
 c_734510.fn = (function_type)__lambda_10;
c_734510.num_args = 1;
c_734510.num_elements = 2;
c_734510.elements = (object *)e_734516;
c_734510.elements[0] = ((closureN)self_734459)->elements[0];
c_734510.elements[1] = r_734374;

return_closcall2(data,  __glo_delete_67_libs_system_91calls,  &c_734510, ((closureN)self_734459)->elements[1]);; 
}

static void __lambda_10(void *data, int argc, object self_734460, object r_734373) {
  

return_closcall1(data,  ((closureN)self_734460)->elements[0],  Cyc_cdr(data, ((closureN)self_734460)->elements[1]));; 
}

void c_libsindex_inlinable_lambdas(void *data, int argc, closure _, object cont){ 
(((closure)cont)->fn)(data, 1, cont, NULL);
 } 
void c_libsindex_entry_pt_first_lambda(data, argc, cont,value) void *data; int argc; closure cont; object value;{ 
Cyc_set_globals_changed((gc_thread_data *)data);
  quote__85default_91local_91index_85 = find_or_add_symbol("*default-local-index*");
  quote_match = find_or_add_symbol("match");

  add_global("__glo_lib_91init_117libsindex_libs_index", (object *) &__glo_lib_91init_117libsindex_libs_index);
  add_global("__glo_unregister_91installed_91package_67_libs_index", (object *) &__glo_unregister_91installed_91package_67_libs_index);
  add_global("__glo_register_91installed_91package_67_libs_index", (object *) &__glo_register_91installed_91package_67_libs_index);
  add_global("__glo_get_91local_91index_libs_index", (object *) &__glo_get_91local_91index_libs_index);
  add_global("__glo_local_91index_91contains_127_libs_index", (object *) &__glo_local_91index_91contains_127_libs_index);
  add_global("__glo__85default_91local_91index_85_libs_index", (object *) &__glo__85default_91local_91index_85_libs_index);
  add_global("__glo_pkg_91info_libs_index", (object *) &__glo_pkg_91info_libs_index);
  add_global("__glo_get_91index_libs_index", (object *) &__glo_get_91index_libs_index);
  add_global("__glo__85default_91index_91url_85_libs_index", (object *) &__glo__85default_91index_91url_85_libs_index);
  add_symbol(quote__85default_91local_91index_85);
  add_symbol(quote_match);
  mclosure0(c_734753, (function_type)__lambda_42);c_734753.num_args = 0; 
  __glo_lib_91init_117libsindex_libs_index = &c_734753; 
  mclosure0(c_734723, (function_type)__lambda_35);c_734723.num_args = 1; 
  __glo_unregister_91installed_91package_67_libs_index = &c_734723; 
  mclosure0(c_734679, (function_type)__lambda_27);c_734679.num_args = 5; 
  __glo_register_91installed_91package_67_libs_index = &c_734679; 
  mclosure0(c_734671, (function_type)__lambda_26);c_734671.num_args = 0; 
  __glo_get_91local_91index_libs_index = &c_734671; 
  mclosure0(c_734592, (function_type)__lambda_17);c_734592.num_args = 4; 
  __glo_local_91index_91contains_127_libs_index = &c_734592; 
  mclosure0(c_734534, (function_type)__lambda_11);c_734534.num_args = 2; 
  __glo_pkg_91info_libs_index = &c_734534; 
  mclosure0(c_734492, (function_type)__lambda_1);c_734492.num_args = 0; 
  __glo_get_91index_libs_index = &c_734492; 
  __glo__85default_91local_91index_85_libs_index = boolean_f; 
  make_utf8_string_with_len(c_734491, "https://raw.githubusercontent.com/cyclone-scheme/cyclone-winds/master/indexes/index.scm", 87, 87); 
  __glo__85default_91index_91url_85_libs_index = &c_734491; 

  mclosure0(clo_734771, c_libsindex_inlinable_lambdas); make_pair(pair_734770, find_or_add_symbol("c_libsindex_inlinable_lambdas"), &clo_734771);
  make_cvar(cvar_734772, (object *)&__glo_lib_91init_117libsindex_libs_index);make_pair(pair_734773, find_or_add_symbol("lib-init:libsindex"), &cvar_734772);
  make_cvar(cvar_734774, (object *)&__glo_unregister_91installed_91package_67_libs_index);make_pair(pair_734775, find_or_add_symbol("unregister-installed-package!"), &cvar_734774);
  make_cvar(cvar_734776, (object *)&__glo_register_91installed_91package_67_libs_index);make_pair(pair_734777, find_or_add_symbol("register-installed-package!"), &cvar_734776);
  make_cvar(cvar_734778, (object *)&__glo_get_91local_91index_libs_index);make_pair(pair_734779, find_or_add_symbol("get-local-index"), &cvar_734778);
  make_cvar(cvar_734780, (object *)&__glo_local_91index_91contains_127_libs_index);make_pair(pair_734781, find_or_add_symbol("local-index-contains?"), &cvar_734780);
  make_cvar(cvar_734782, (object *)&__glo__85default_91local_91index_85_libs_index);make_pair(pair_734783, find_or_add_symbol("*default-local-index*"), &cvar_734782);
  make_cvar(cvar_734784, (object *)&__glo_pkg_91info_libs_index);make_pair(pair_734785, find_or_add_symbol("pkg-info"), &cvar_734784);
  make_cvar(cvar_734786, (object *)&__glo_get_91index_libs_index);make_pair(pair_734787, find_or_add_symbol("get-index"), &cvar_734786);
  make_cvar(cvar_734788, (object *)&__glo__85default_91index_91url_85_libs_index);make_pair(pair_734789, find_or_add_symbol("*default-index-url*"), &cvar_734788);
make_pair(c_734799, &pair_734770,Cyc_global_variables);
make_pair(c_734798, &pair_734773, &c_734799);
make_pair(c_734797, &pair_734775, &c_734798);
make_pair(c_734796, &pair_734777, &c_734797);
make_pair(c_734795, &pair_734779, &c_734796);
make_pair(c_734794, &pair_734781, &c_734795);
make_pair(c_734793, &pair_734783, &c_734794);
make_pair(c_734792, &pair_734785, &c_734793);
make_pair(c_734791, &pair_734787, &c_734792);
make_pair(c_734790, &pair_734789, &c_734791);
Cyc_global_variables = &c_734790;
cont = ((closure1_type *)cont)->element;
(((closure)__glo_lib_91init_117libsindex_libs_index)->fn)(data, 1, cont, cont);
}
void c_libsindex_entry_pt(data, argc, cont,value) void *data; int argc; closure cont; object value;{ 
  register_library("libs_index");
  c_libsindex_entry_pt_first_lambda(data, argc, cont,value);
}
