/**
 ** This file was automatically generated by the Cyclone scheme compiler
 ** http://justinethier.github.io/cyclone/
 **
 ** (c) 2014-2017 Justin Ethier
 ** Version 0.5.1 
 **
 **/

#define closcall1(td, clo,a1) \
if (type_is_pair_prim(clo)) { \
   Cyc_apply(td, 0, (closure)(a1), clo); \
} else { \
   ((clo)->fn)(td, 1, clo,a1);\
}
#define return_closcall1(td, clo,a1) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[1]; buf[0] = a1;\
     GC(td, clo, buf, 1); \
     return; \
 } else {\
     closcall1(td, (closure) (clo),a1); \
     return;\
 } \
}

#define return_direct1(td, _fn,a1) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[1]; buf[0] = a1; \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 1); \
     return; \
 } else { \
     (_fn)(td, 1, (closure)_fn,a1); \
 }}

#define closcall2(td, clo,a1,a2) \
if (type_is_pair_prim(clo)) { \
   Cyc_apply(td, 1, (closure)(a1), clo,a2); \
} else { \
   ((clo)->fn)(td, 2, clo,a1,a2);\
}
#define return_closcall2(td, clo,a1,a2) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[2]; buf[0] = a1;buf[1] = a2;\
     GC(td, clo, buf, 2); \
     return; \
 } else {\
     closcall2(td, (closure) (clo),a1,a2); \
     return;\
 } \
}

#define return_direct2(td, _fn,a1,a2) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[2]; buf[0] = a1;buf[1] = a2; \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 2); \
     return; \
 } else { \
     (_fn)(td, 2, (closure)_fn,a1,a2); \
 }}

#define closcall3(td, clo,a1,a2,a3) \
if (type_is_pair_prim(clo)) { \
   Cyc_apply(td, 2, (closure)(a1), clo,a2,a3); \
} else { \
   ((clo)->fn)(td, 3, clo,a1,a2,a3);\
}
#define return_closcall3(td, clo,a1,a2,a3) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3;\
     GC(td, clo, buf, 3); \
     return; \
 } else {\
     closcall3(td, (closure) (clo),a1,a2,a3); \
     return;\
 } \
}

#define return_direct3(td, _fn,a1,a2,a3) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3; \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 3); \
     return; \
 } else { \
     (_fn)(td, 3, (closure)_fn,a1,a2,a3); \
 }}

#include "cyclone/types.h"
object __glo_lib_91init_117scheme_191char_scheme__char = NULL;
object __glo_string_91foldcase_scheme__char = NULL;
object __glo_string_91downcase_scheme__char = NULL;
object __glo_string_91upcase_scheme__char = NULL;
object __glo_digit_91value_scheme__char = NULL;
object __glo_char_91whitespace_127_scheme__char = NULL;
object __glo_char_91numeric_127_scheme__char = NULL;
object __glo_char_91lower_91case_127_191_191inline_191_191_scheme__char = NULL;
object __glo_char_91lower_91case_127_scheme__char = NULL;
object __glo_char_91upper_91case_127_191_191inline_191_191_scheme__char = NULL;
object __glo_char_91upper_91case_127_scheme__char = NULL;
object __glo_char_91alphabetic_127_scheme__char = NULL;
object __glo_string_91ci_125_123_127_scheme__char = NULL;
object __glo_string_91ci_125_127_scheme__char = NULL;
object __glo_string_91ci_121_123_127_scheme__char = NULL;
object __glo_string_91ci_121_127_scheme__char = NULL;
object __glo_string_91ci_123_127_scheme__char = NULL;
object __glo_char_91ci_125_127_scheme__char = NULL;
object __glo_char_91ci_125_123_127_scheme__char = NULL;
object __glo_char_91ci_121_127_scheme__char = NULL;
object __glo_char_91ci_121_123_127_scheme__char = NULL;
object __glo_char_91ci_123_127_scheme__char = NULL;
object __glo_char_91foldcase_scheme__char = NULL;
object __glo_char_91downcase_scheme__char = NULL;
object __glo_char_91upcase_scheme__char = NULL;
extern object __glo_member_scheme_base;
extern object __glo_assoc_scheme_base;
extern object __glo_cons_91source_scheme_base;
extern object __glo_syntax_91rules_scheme_base;
extern object __glo_letrec_85_scheme_base;
extern object __glo_guard_scheme_base;
extern object __glo_guard_91aux_scheme_base;
extern object __glo_define_91record_91type_scheme_base;
extern object __glo_record_127_scheme_base;
extern object __glo_register_91simple_91type_scheme_base;
extern object __glo_make_91type_91predicate_scheme_base;
extern object __glo_make_91constructor_scheme_base;
extern object __glo_make_91getter_scheme_base;
extern object __glo_make_91setter_scheme_base;
extern object __glo_slot_91set_67_scheme_base;
extern object __glo_type_91slot_91offset_scheme_base;
extern object __glo_receive_scheme_base;
extern object __glo_abs_scheme_base;
extern object __glo_max_scheme_base;
extern object __glo_min_scheme_base;
extern object __glo_modulo_scheme_base;
extern object __glo_floor_91remainder_scheme_base;
extern object __glo_even_127_scheme_base;
extern object __glo_exact_91integer_127_scheme_base;
extern object __glo_exact_91integer_91sqrt_scheme_base;
extern object __glo_exact_127_scheme_base;
extern object __glo_inexact_127_scheme_base;
extern object __glo_odd_127_scheme_base;
extern object __glo_complex_127_scheme_base;
extern object __glo_rational_127_scheme_base;
extern object __glo_bignum_127_scheme_base;
extern object __glo_gcd_scheme_base;
extern object __glo_lcm_scheme_base;
extern object __glo_quotient_scheme_base;
extern object __glo_remainder_scheme_base;
extern object __glo_truncate_91quotient_scheme_base;
extern object __glo_truncate_91remainder_scheme_base;
extern object __glo_truncate_95_scheme_base;
extern object __glo_floor_91quotient_scheme_base;
extern object __glo_floor_91remainder_scheme_base;
extern object __glo_floor_95_scheme_base;
extern object __glo_square_scheme_base;
extern object __glo_expt_scheme_base;
extern object __glo_call_91with_91current_91continuation_scheme_base;
extern object __glo_call_95cc_scheme_base;
extern object __glo_call_91with_91values_scheme_base;
extern object __glo_dynamic_91wind_scheme_base;
extern object __glo_values_scheme_base;
extern object __glo_char_123_127_scheme_base;
extern object __glo_char_121_127_scheme_base;
extern object __glo_char_125_127_scheme_base;
extern object __glo_char_121_123_127_scheme_base;
extern object __glo_char_125_123_127_scheme_base;
extern object __glo_string_123_127_scheme_base;
extern object __glo_string_121_127_scheme_base;
extern object __glo_string_121_123_127_scheme_base;
extern object __glo_string_125_127_scheme_base;
extern object __glo_string_125_123_127_scheme_base;
extern object __glo_foldl_scheme_base;
extern object __glo_foldr_scheme_base;
extern object __glo_not_scheme_base;
extern object __glo_list_127_scheme_base;
extern object __glo_zero_127_scheme_base;
extern object __glo_positive_127_scheme_base;
extern object __glo_negative_127_scheme_base;
extern object __glo_append_scheme_base;
extern object __glo__list_scheme_base;
extern object __glo_make_91list_scheme_base;
extern object __glo_list_91copy_scheme_base;
extern object __glo_map_scheme_base;
extern object __glo_for_91each_scheme_base;
extern object __glo_list_91tail_scheme_base;
extern object __glo_list_91ref_scheme_base;
extern object __glo_list_91set_67_scheme_base;
extern object __glo_reverse_scheme_base;
extern object __glo_boolean_123_127_scheme_base;
extern object __glo_symbol_123_127_scheme_base;
extern object __glo_Cyc_91obj_123_127_scheme_base;
extern object __glo_vector_scheme_base;
extern object __glo_vector_91append_scheme_base;
extern object __glo_vector_91copy_scheme_base;
extern object __glo_vector_91copy_67_scheme_base;
extern object __glo_vector_91fill_67_scheme_base;
extern object __glo_vector_91_125list_scheme_base;
extern object __glo_vector_91_125string_scheme_base;
extern object __glo_vector_91map_scheme_base;
extern object __glo_vector_91for_91each_scheme_base;
extern object __glo_make_91string_scheme_base;
extern object __glo_string_scheme_base;
extern object __glo_string_91copy_scheme_base;
extern object __glo_string_91copy_67_scheme_base;
extern object __glo_string_91fill_67_scheme_base;
extern object __glo_string_91_125list_scheme_base;
extern object __glo_string_91_125vector_scheme_base;
extern object __glo_string_91map_scheme_base;
extern object __glo_string_91for_91each_scheme_base;
extern object __glo_make_91parameter_scheme_base;
extern object __glo_current_91output_91port_scheme_base;
extern object __glo_current_91input_91port_scheme_base;
extern object __glo_current_91error_91port_scheme_base;
extern object __glo_call_91with_91port_scheme_base;
extern object __glo_error_scheme_base;
extern object __glo_raise_scheme_base;
extern object __glo_raise_91continuable_scheme_base;
extern object __glo_with_91handler_scheme_base;
extern object __glo_with_91exception_91handler_scheme_base;
extern object __glo_Cyc_91add_91exception_91handler_scheme_base;
extern object __glo_Cyc_91remove_91exception_91handler_scheme_base;
extern object __glo_newline_scheme_base;
extern object __glo_write_91char_scheme_base;
extern object __glo_write_91string_scheme_base;
extern object __glo_flush_91output_91port_scheme_base;
extern object __glo_read_91line_scheme_base;
extern object __glo_read_91string_scheme_base;
extern object __glo_input_91port_127_scheme_base;
extern object __glo_output_91port_127_scheme_base;
extern object __glo_input_91port_91open_127_scheme_base;
extern object __glo_output_91port_91open_127_scheme_base;
extern object __glo_get_91output_91string_scheme_base;
extern object __glo_open_91output_91string_scheme_base;
extern object __glo_open_91input_91string_scheme_base;
extern object __glo_get_91output_91bytevector_scheme_base;
extern object __glo_open_91input_91bytevector_scheme_base;
extern object __glo_open_91output_91bytevector_scheme_base;
extern object __glo_features_scheme_base;
extern object __glo_Cyc_91version_scheme_base;
extern object __glo_any_scheme_base;
extern object __glo_every_scheme_base;
extern object __glo_and_scheme_base;
extern object __glo_or_scheme_base;
extern object __glo_let_scheme_base;
extern object __glo_let_85_scheme_base;
extern object __glo_letrec_scheme_base;
extern object __glo_let_85_91values_scheme_base;
extern object __glo_let_91values_scheme_base;
extern object __glo_begin_scheme_base;
extern object __glo__case_scheme_base;
extern object __glo_cond_scheme_base;
extern object __glo_cond_91expand_scheme_base;
extern object __glo__do_scheme_base;
extern object __glo_when_scheme_base;
extern object __glo_unless_scheme_base;
extern object __glo_quasiquote_scheme_base;
extern object __glo_floor_scheme_base;
extern object __glo_ceiling_scheme_base;
extern object __glo_truncate_scheme_base;
extern object __glo_round_scheme_base;
extern object __glo_exact_scheme_base;
extern object __glo_inexact_scheme_base;
extern object __glo_eof_91object_scheme_base;
extern object __glo_syntax_91error_scheme_base;
extern object __glo_bytevector_91copy_scheme_base;
extern object __glo_bytevector_91copy_67_scheme_base;
extern object __glo_utf8_91_125string_scheme_base;
extern object __glo_string_91_125utf8_scheme_base;
extern object __glo_denominator_scheme_base;
extern object __glo_numerator_scheme_base;
extern object __glo_parameterize_scheme_base;
#include "cyclone/runtime.h"
static void __lambda_42(void *data, int argc, closure _,object k_7345) ;
static void __lambda_41(void *data, int argc, closure _,object k_7349, object str_736) ;
static void __lambda_40(void *data, int argc, closure _,object k_7352, object str_737) ;
static void __lambda_39(void *data, int argc, closure _,object k_7355, object str_738) ;
static void __lambda_38(void *data, int argc, closure _,object k_7358, object c_739) ;
static void __lambda_37(void *data, int argc, object self_73159, object r_7359) ;
static void __lambda_36(void *data, int argc, closure _,object k_7364, object c_7310) ;
static void __lambda_35(void *data, int argc, closure _,object k_7369, object c_7311) ;
static object __lambda_34(void *data, object ptr,object c_7312) ;
static void __lambda_33(void *data, int argc, closure _,object k_7374, object c_7312) ;
static object __lambda_32(void *data, object ptr,object c_7313) ;
static void __lambda_31(void *data, int argc, closure _,object k_7378, object c_7313) ;
static void __lambda_30(void *data, int argc, closure _,object k_7382, object c_7314) ;
static void __lambda_29(void *data, int argc, object self_73160, object tmp_732_7315) ;
static void __lambda_28(void *data, int argc, closure _,object k_7386, object s1_7317, object s2_7316) ;
static void __lambda_27(void *data, int argc, object self_73161, object r_7388) ;
static void __lambda_26(void *data, int argc, object self_73162, object r_7387) ;
static void __lambda_25(void *data, int argc, closure _,object k_7391, object s1_7319, object s2_7318) ;
static void __lambda_24(void *data, int argc, object self_73163, object r_7393) ;
static void __lambda_23(void *data, int argc, object self_73164, object r_7392) ;
static void __lambda_22(void *data, int argc, closure _,object k_7396, object s1_7321, object s2_7320) ;
static void __lambda_21(void *data, int argc, object self_73165, object r_7398) ;
static void __lambda_20(void *data, int argc, object self_73166, object r_7397) ;
static void __lambda_19(void *data, int argc, closure _,object k_73101, object s1_7323, object s2_7322) ;
static void __lambda_18(void *data, int argc, object self_73167, object r_73103) ;
static void __lambda_17(void *data, int argc, object self_73168, object r_73102) ;
static void __lambda_16(void *data, int argc, closure _,object k_73106, object s1_7325, object s2_7324) ;
static void __lambda_15(void *data, int argc, object self_73169, object r_73108) ;
static void __lambda_14(void *data, int argc, object self_73170, object r_73107) ;
static void __lambda_13(void *data, int argc, closure _,object k_73111, object c1_7328, object c2_7327, object cs_7326_raw, ...) ;
static void __lambda_12(void *data, int argc, object self_73171, object r_73112) ;
static void __lambda_11(void *data, int argc, closure _,object k_73117, object c1_7331, object c2_7330, object cs_7329_raw, ...) ;
static void __lambda_10(void *data, int argc, object self_73172, object r_73118) ;
static void __lambda_9(void *data, int argc, closure _,object k_73123, object c1_7334, object c2_7333, object cs_7332_raw, ...) ;
static void __lambda_8(void *data, int argc, object self_73173, object r_73124) ;
static void __lambda_7(void *data, int argc, closure _,object k_73129, object c1_7337, object c2_7336, object cs_7335_raw, ...) ;
static void __lambda_6(void *data, int argc, object self_73174, object r_73130) ;
static void __lambda_5(void *data, int argc, closure _,object k_73135, object c1_7340, object c2_7339, object cs_7338_raw, ...) ;
static void __lambda_4(void *data, int argc, object self_73175, object r_73136) ;
static void __lambda_3(void *data, int argc, closure _,object k_73143, object c_7341) ;
static void __lambda_2(void *data, int argc, object self_73176, object r_73144) ;
static void __lambda_1(void *data, int argc, closure _,object k_73152, object c_7342) ;
static void __lambda_0(void *data, int argc, object self_73177, object r_73153) ;

static void __lambda_42(void *data, int argc, closure _,object k_7345) {
  Cyc_st_add(data, "scheme/char.sld:lib-init:scheme_char");
return_closcall1(data,  k_7345,  global_set(__glo_char_91foldcase_scheme__char, __glo_char_91downcase_scheme__char));; 
}

static void __lambda_41(void *data, int argc, closure _,object k_7349, object str_736) {
  Cyc_st_add(data, "scheme/char.sld:string-foldcase");
return_closcall3(data,  __glo_string_91map_scheme_base,  k_7349, __glo_char_91foldcase_scheme__char, str_736);; 
}

static void __lambda_40(void *data, int argc, closure _,object k_7352, object str_737) {
  Cyc_st_add(data, "scheme/char.sld:string-downcase");
return_closcall3(data,  __glo_string_91map_scheme_base,  k_7352, __glo_char_91downcase_scheme__char, str_737);; 
}

static void __lambda_39(void *data, int argc, closure _,object k_7355, object str_738) {
  Cyc_st_add(data, "scheme/char.sld:string-upcase");
return_closcall3(data,  __glo_string_91map_scheme_base,  k_7355, __glo_char_91upcase_scheme__char, str_738);; 
}

static void __lambda_38(void *data, int argc, closure _,object k_7358, object c_739) {
  Cyc_st_add(data, "scheme/char.sld:digit-value");

closureN_type c_73418;
c_73418.hdr.mark = gc_color_red;
 c_73418.hdr.grayed = 0;
c_73418.tag = closureN_tag;
 c_73418.fn = (function_type)__lambda_37;
c_73418.num_args = 1;
c_73418.num_elements = 2;
c_73418.elements = (object *)alloca(sizeof(object) * 2);
c_73418.elements[0] = c_739;
c_73418.elements[1] = k_7358;

return_closcall2(data,  __glo_char_91numeric_127_scheme__char,  &c_73418, c_739);; 
}

static void __lambda_37(void *data, int argc, object self_73159, object r_7359) {
  if( (boolean_f != r_7359) ){ 
  
common_type local_73423; object c_73424 = Cyc_fast_sub(data,&local_73423,Cyc_char2integer(((closureN)self_73159)->elements[0]), Cyc_char2integer(obj_char2obj(48)));
return_closcall1(data,  ((closureN)self_73159)->elements[1],  c_73424);
} else { 
  return_closcall1(data,  ((closureN)self_73159)->elements[1],  boolean_f);}
; 
}

static void __lambda_36(void *data, int argc, closure _,object k_7364, object c_7310) {
  Cyc_st_add(data, "scheme/char.sld:char-whitespace?");
  make_pair(c_73413,obj_char2obj(10),NULL);
  make_pair(c_73412,obj_char2obj(13),&c_73413);
  make_pair(c_73411,obj_char2obj(32),&c_73412);
  make_pair(c_73410,obj_char2obj(9),&c_73411);
if( (boolean_f != memberp(data, c_7310, &c_73410)) ){ 
  return_closcall1(data,  k_7364,  boolean_t);
} else { 
  return_closcall1(data,  k_7364,  boolean_f);}
; 
}

static void __lambda_35(void *data, int argc, closure _,object k_7369, object c_7311) {
  Cyc_st_add(data, "scheme/char.sld:char-numeric?");
  make_pair(c_73404,obj_char2obj(57),NULL);
  make_pair(c_73403,obj_char2obj(56),&c_73404);
  make_pair(c_73402,obj_char2obj(55),&c_73403);
  make_pair(c_73401,obj_char2obj(54),&c_73402);
  make_pair(c_73400,obj_char2obj(53),&c_73401);
  make_pair(c_73399,obj_char2obj(52),&c_73400);
  make_pair(c_73398,obj_char2obj(51),&c_73399);
  make_pair(c_73397,obj_char2obj(50),&c_73398);
  make_pair(c_73396,obj_char2obj(49),&c_73397);
  make_pair(c_73395,obj_char2obj(48),&c_73396);
if( (boolean_f != memberp(data, c_7311, &c_73395)) ){ 
  return_closcall1(data,  k_7369,  boolean_t);
} else { 
  return_closcall1(data,  k_7369,  boolean_f);}
; 
}

static object __lambda_34(void *data, object ptr,object c_7312) {
  Cyc_st_add(data, "scheme/char.sld:char-lower-case?");
  object c_73386 = Cyc_char_gte_op(data,c_7312, obj_char2obj(97));
if( (boolean_f != c_73386) ){ 
  
object c_73390 = Cyc_char_lte_op(data,c_7312, obj_char2obj(122));
return_copy(ptr,  c_73390);
} else { 
  return_copy(ptr,  boolean_f);}
; 
}

static void __lambda_33(void *data, int argc, closure _,object k_7374, object c_7312) {
  Cyc_st_add(data, "scheme/char.sld:char-lower-case?");
  object c_73377 = Cyc_char_gte_op(data,c_7312, obj_char2obj(97));
if( (boolean_f != c_73377) ){ 
  
object c_73381 = Cyc_char_lte_op(data,c_7312, obj_char2obj(122));
return_closcall1(data,  k_7374,  c_73381);
} else { 
  return_closcall1(data,  k_7374,  boolean_f);}
; 
}

static object __lambda_32(void *data, object ptr,object c_7313) {
  Cyc_st_add(data, "scheme/char.sld:char-upper-case?");
  object c_73368 = Cyc_char_gte_op(data,c_7313, obj_char2obj(65));
if( (boolean_f != c_73368) ){ 
  
object c_73372 = Cyc_char_lte_op(data,c_7313, obj_char2obj(90));
return_copy(ptr,  c_73372);
} else { 
  return_copy(ptr,  boolean_f);}
; 
}

static void __lambda_31(void *data, int argc, closure _,object k_7378, object c_7313) {
  Cyc_st_add(data, "scheme/char.sld:char-upper-case?");
  object c_73359 = Cyc_char_gte_op(data,c_7313, obj_char2obj(65));
if( (boolean_f != c_73359) ){ 
  
object c_73363 = Cyc_char_lte_op(data,c_7313, obj_char2obj(90));
return_closcall1(data,  k_7378,  c_73363);
} else { 
  return_closcall1(data,  k_7378,  boolean_f);}
; 
}

static void __lambda_30(void *data, int argc, closure _,object k_7382, object c_7314) {
  Cyc_st_add(data, "scheme/char.sld:char-alphabetic?");

closureN_type c_73350;
c_73350.hdr.mark = gc_color_red;
 c_73350.hdr.grayed = 0;
c_73350.tag = closureN_tag;
 c_73350.fn = (function_type)__lambda_29;
c_73350.num_args = 1;
c_73350.num_elements = 2;
c_73350.elements = (object *)alloca(sizeof(object) * 2);
c_73350.elements[0] = c_7314;
c_73350.elements[1] = k_7382;

return_closcall2(data,  __glo_char_91upper_91case_127_scheme__char,  &c_73350, c_7314);; 
}

static void __lambda_29(void *data, int argc, object self_73160, object tmp_732_7315) {
  if( (boolean_f != tmp_732_7315) ){ 
  return_closcall1(data,  ((closureN)self_73160)->elements[1],  tmp_732_7315);
} else { 
  return_closcall2(data,  __glo_char_91lower_91case_127_scheme__char,  ((closureN)self_73160)->elements[1], ((closureN)self_73160)->elements[0]);}
; 
}

static void __lambda_28(void *data, int argc, closure _,object k_7386, object s1_7317, object s2_7316) {
  Cyc_st_add(data, "scheme/char.sld:string-ci>=?");

closureN_type c_73340;
c_73340.hdr.mark = gc_color_red;
 c_73340.hdr.grayed = 0;
c_73340.tag = closureN_tag;
 c_73340.fn = (function_type)__lambda_27;
c_73340.num_args = 1;
c_73340.num_elements = 1;
c_73340.elements = (object *)alloca(sizeof(object) * 1);
c_73340.elements[0] = k_7386;

return_closcall3(data,  __glo__list_scheme_base,  &c_73340, s1_7317, s2_7316);; 
}

static void __lambda_27(void *data, int argc, object self_73161, object r_7388) {
  
closureN_type c_73342;
c_73342.hdr.mark = gc_color_red;
 c_73342.hdr.grayed = 0;
c_73342.tag = closureN_tag;
 c_73342.fn = (function_type)__lambda_26;
c_73342.num_args = 1;
c_73342.num_elements = 1;
c_73342.elements = (object *)alloca(sizeof(object) * 1);
c_73342.elements[0] = ((closureN)self_73161)->elements[0];

return_closcall3(data,  __glo_map_scheme_base,  &c_73342, __glo_string_91foldcase_scheme__char, r_7388);; 
}

static void __lambda_26(void *data, int argc, object self_73162, object r_7387) {
  
object c_73347 = apply_va(data,  ((closureN)self_73162)->elements[0],2,__glo_string_125_123_127_scheme_base, r_7387);
return_closcall1(data,  ((closureN)self_73162)->elements[0],  c_73347);; 
}

static void __lambda_25(void *data, int argc, closure _,object k_7391, object s1_7319, object s2_7318) {
  Cyc_st_add(data, "scheme/char.sld:string-ci>?");

closureN_type c_73330;
c_73330.hdr.mark = gc_color_red;
 c_73330.hdr.grayed = 0;
c_73330.tag = closureN_tag;
 c_73330.fn = (function_type)__lambda_24;
c_73330.num_args = 1;
c_73330.num_elements = 1;
c_73330.elements = (object *)alloca(sizeof(object) * 1);
c_73330.elements[0] = k_7391;

return_closcall3(data,  __glo__list_scheme_base,  &c_73330, s1_7319, s2_7318);; 
}

static void __lambda_24(void *data, int argc, object self_73163, object r_7393) {
  
closureN_type c_73332;
c_73332.hdr.mark = gc_color_red;
 c_73332.hdr.grayed = 0;
c_73332.tag = closureN_tag;
 c_73332.fn = (function_type)__lambda_23;
c_73332.num_args = 1;
c_73332.num_elements = 1;
c_73332.elements = (object *)alloca(sizeof(object) * 1);
c_73332.elements[0] = ((closureN)self_73163)->elements[0];

return_closcall3(data,  __glo_map_scheme_base,  &c_73332, __glo_string_91foldcase_scheme__char, r_7393);; 
}

static void __lambda_23(void *data, int argc, object self_73164, object r_7392) {
  
object c_73337 = apply_va(data,  ((closureN)self_73164)->elements[0],2,__glo_string_125_127_scheme_base, r_7392);
return_closcall1(data,  ((closureN)self_73164)->elements[0],  c_73337);; 
}

static void __lambda_22(void *data, int argc, closure _,object k_7396, object s1_7321, object s2_7320) {
  Cyc_st_add(data, "scheme/char.sld:string-ci<=?");

closureN_type c_73320;
c_73320.hdr.mark = gc_color_red;
 c_73320.hdr.grayed = 0;
c_73320.tag = closureN_tag;
 c_73320.fn = (function_type)__lambda_21;
c_73320.num_args = 1;
c_73320.num_elements = 1;
c_73320.elements = (object *)alloca(sizeof(object) * 1);
c_73320.elements[0] = k_7396;

return_closcall3(data,  __glo__list_scheme_base,  &c_73320, s1_7321, s2_7320);; 
}

static void __lambda_21(void *data, int argc, object self_73165, object r_7398) {
  
closureN_type c_73322;
c_73322.hdr.mark = gc_color_red;
 c_73322.hdr.grayed = 0;
c_73322.tag = closureN_tag;
 c_73322.fn = (function_type)__lambda_20;
c_73322.num_args = 1;
c_73322.num_elements = 1;
c_73322.elements = (object *)alloca(sizeof(object) * 1);
c_73322.elements[0] = ((closureN)self_73165)->elements[0];

return_closcall3(data,  __glo_map_scheme_base,  &c_73322, __glo_string_91foldcase_scheme__char, r_7398);; 
}

static void __lambda_20(void *data, int argc, object self_73166, object r_7397) {
  
object c_73327 = apply_va(data,  ((closureN)self_73166)->elements[0],2,__glo_string_121_123_127_scheme_base, r_7397);
return_closcall1(data,  ((closureN)self_73166)->elements[0],  c_73327);; 
}

static void __lambda_19(void *data, int argc, closure _,object k_73101, object s1_7323, object s2_7322) {
  Cyc_st_add(data, "scheme/char.sld:string-ci<?");

closureN_type c_73310;
c_73310.hdr.mark = gc_color_red;
 c_73310.hdr.grayed = 0;
c_73310.tag = closureN_tag;
 c_73310.fn = (function_type)__lambda_18;
c_73310.num_args = 1;
c_73310.num_elements = 1;
c_73310.elements = (object *)alloca(sizeof(object) * 1);
c_73310.elements[0] = k_73101;

return_closcall3(data,  __glo__list_scheme_base,  &c_73310, s1_7323, s2_7322);; 
}

static void __lambda_18(void *data, int argc, object self_73167, object r_73103) {
  
closureN_type c_73312;
c_73312.hdr.mark = gc_color_red;
 c_73312.hdr.grayed = 0;
c_73312.tag = closureN_tag;
 c_73312.fn = (function_type)__lambda_17;
c_73312.num_args = 1;
c_73312.num_elements = 1;
c_73312.elements = (object *)alloca(sizeof(object) * 1);
c_73312.elements[0] = ((closureN)self_73167)->elements[0];

return_closcall3(data,  __glo_map_scheme_base,  &c_73312, __glo_string_91foldcase_scheme__char, r_73103);; 
}

static void __lambda_17(void *data, int argc, object self_73168, object r_73102) {
  
object c_73317 = apply_va(data,  ((closureN)self_73168)->elements[0],2,__glo_string_121_127_scheme_base, r_73102);
return_closcall1(data,  ((closureN)self_73168)->elements[0],  c_73317);; 
}

static void __lambda_16(void *data, int argc, closure _,object k_73106, object s1_7325, object s2_7324) {
  Cyc_st_add(data, "scheme/char.sld:string-ci=?");

closureN_type c_73300;
c_73300.hdr.mark = gc_color_red;
 c_73300.hdr.grayed = 0;
c_73300.tag = closureN_tag;
 c_73300.fn = (function_type)__lambda_15;
c_73300.num_args = 1;
c_73300.num_elements = 1;
c_73300.elements = (object *)alloca(sizeof(object) * 1);
c_73300.elements[0] = k_73106;

return_closcall3(data,  __glo__list_scheme_base,  &c_73300, s1_7325, s2_7324);; 
}

static void __lambda_15(void *data, int argc, object self_73169, object r_73108) {
  
closureN_type c_73302;
c_73302.hdr.mark = gc_color_red;
 c_73302.hdr.grayed = 0;
c_73302.tag = closureN_tag;
 c_73302.fn = (function_type)__lambda_14;
c_73302.num_args = 1;
c_73302.num_elements = 1;
c_73302.elements = (object *)alloca(sizeof(object) * 1);
c_73302.elements[0] = ((closureN)self_73169)->elements[0];

return_closcall3(data,  __glo_map_scheme_base,  &c_73302, __glo_string_91foldcase_scheme__char, r_73108);; 
}

static void __lambda_14(void *data, int argc, object self_73170, object r_73107) {
  
object c_73307 = apply_va(data,  ((closureN)self_73170)->elements[0],2,__glo_string_123_127_scheme_base, r_73107);
return_closcall1(data,  ((closureN)self_73170)->elements[0],  c_73307);; 
}

static void __lambda_13(void *data, int argc, closure _,object k_73111, object c1_7328, object c2_7327, object cs_7326_raw, ...) {
load_varargs(cs_7326, cs_7326_raw, argc - 3);
  Cyc_st_add(data, "scheme/char.sld:char-ci>?");

closureN_type c_73286;
c_73286.hdr.mark = gc_color_red;
 c_73286.hdr.grayed = 0;
c_73286.tag = closureN_tag;
 c_73286.fn = (function_type)__lambda_12;
c_73286.num_args = 1;
c_73286.num_elements = 1;
c_73286.elements = (object *)alloca(sizeof(object) * 1);
c_73286.elements[0] = k_73111;


make_pair(c_73297,c2_7327, cs_7326);

make_pair(c_73294,c1_7328, &c_73297);
return_closcall3(data,  __glo_map_scheme_base,  &c_73286, __glo_char_91foldcase_scheme__char, &c_73294);; 
}

static void __lambda_12(void *data, int argc, object self_73171, object r_73112) {
  
object c_73291 = apply_va(data,  ((closureN)self_73171)->elements[0],2,__glo_char_125_127_scheme_base, r_73112);
return_closcall1(data,  ((closureN)self_73171)->elements[0],  c_73291);; 
}

static void __lambda_11(void *data, int argc, closure _,object k_73117, object c1_7331, object c2_7330, object cs_7329_raw, ...) {
load_varargs(cs_7329, cs_7329_raw, argc - 3);
  Cyc_st_add(data, "scheme/char.sld:char-ci>=?");

closureN_type c_73272;
c_73272.hdr.mark = gc_color_red;
 c_73272.hdr.grayed = 0;
c_73272.tag = closureN_tag;
 c_73272.fn = (function_type)__lambda_10;
c_73272.num_args = 1;
c_73272.num_elements = 1;
c_73272.elements = (object *)alloca(sizeof(object) * 1);
c_73272.elements[0] = k_73117;


make_pair(c_73283,c2_7330, cs_7329);

make_pair(c_73280,c1_7331, &c_73283);
return_closcall3(data,  __glo_map_scheme_base,  &c_73272, __glo_char_91foldcase_scheme__char, &c_73280);; 
}

static void __lambda_10(void *data, int argc, object self_73172, object r_73118) {
  
object c_73277 = apply_va(data,  ((closureN)self_73172)->elements[0],2,__glo_char_125_123_127_scheme_base, r_73118);
return_closcall1(data,  ((closureN)self_73172)->elements[0],  c_73277);; 
}

static void __lambda_9(void *data, int argc, closure _,object k_73123, object c1_7334, object c2_7333, object cs_7332_raw, ...) {
load_varargs(cs_7332, cs_7332_raw, argc - 3);
  Cyc_st_add(data, "scheme/char.sld:char-ci<?");

closureN_type c_73258;
c_73258.hdr.mark = gc_color_red;
 c_73258.hdr.grayed = 0;
c_73258.tag = closureN_tag;
 c_73258.fn = (function_type)__lambda_8;
c_73258.num_args = 1;
c_73258.num_elements = 1;
c_73258.elements = (object *)alloca(sizeof(object) * 1);
c_73258.elements[0] = k_73123;


make_pair(c_73269,c2_7333, cs_7332);

make_pair(c_73266,c1_7334, &c_73269);
return_closcall3(data,  __glo_map_scheme_base,  &c_73258, __glo_char_91foldcase_scheme__char, &c_73266);; 
}

static void __lambda_8(void *data, int argc, object self_73173, object r_73124) {
  
object c_73263 = apply_va(data,  ((closureN)self_73173)->elements[0],2,__glo_char_121_127_scheme_base, r_73124);
return_closcall1(data,  ((closureN)self_73173)->elements[0],  c_73263);; 
}

static void __lambda_7(void *data, int argc, closure _,object k_73129, object c1_7337, object c2_7336, object cs_7335_raw, ...) {
load_varargs(cs_7335, cs_7335_raw, argc - 3);
  Cyc_st_add(data, "scheme/char.sld:char-ci<=?");

closureN_type c_73244;
c_73244.hdr.mark = gc_color_red;
 c_73244.hdr.grayed = 0;
c_73244.tag = closureN_tag;
 c_73244.fn = (function_type)__lambda_6;
c_73244.num_args = 1;
c_73244.num_elements = 1;
c_73244.elements = (object *)alloca(sizeof(object) * 1);
c_73244.elements[0] = k_73129;


make_pair(c_73255,c2_7336, cs_7335);

make_pair(c_73252,c1_7337, &c_73255);
return_closcall3(data,  __glo_map_scheme_base,  &c_73244, __glo_char_91foldcase_scheme__char, &c_73252);; 
}

static void __lambda_6(void *data, int argc, object self_73174, object r_73130) {
  
object c_73249 = apply_va(data,  ((closureN)self_73174)->elements[0],2,__glo_char_121_123_127_scheme_base, r_73130);
return_closcall1(data,  ((closureN)self_73174)->elements[0],  c_73249);; 
}

static void __lambda_5(void *data, int argc, closure _,object k_73135, object c1_7340, object c2_7339, object cs_7338_raw, ...) {
load_varargs(cs_7338, cs_7338_raw, argc - 3);
  Cyc_st_add(data, "scheme/char.sld:char-ci=?");

closureN_type c_73230;
c_73230.hdr.mark = gc_color_red;
 c_73230.hdr.grayed = 0;
c_73230.tag = closureN_tag;
 c_73230.fn = (function_type)__lambda_4;
c_73230.num_args = 1;
c_73230.num_elements = 1;
c_73230.elements = (object *)alloca(sizeof(object) * 1);
c_73230.elements[0] = k_73135;


make_pair(c_73241,c2_7339, cs_7338);

make_pair(c_73238,c1_7340, &c_73241);
return_closcall3(data,  __glo_map_scheme_base,  &c_73230, __glo_char_91foldcase_scheme__char, &c_73238);; 
}

static void __lambda_4(void *data, int argc, object self_73175, object r_73136) {
  
object c_73235 = apply_va(data,  ((closureN)self_73175)->elements[0],2,__glo_char_123_127_scheme_base, r_73136);
return_closcall1(data,  ((closureN)self_73175)->elements[0],  c_73235);; 
}

static void __lambda_3(void *data, int argc, closure _,object k_73143, object c_7341) {
  Cyc_st_add(data, "scheme/char.sld:char-downcase");

closureN_type c_73205;
c_73205.hdr.mark = gc_color_red;
 c_73205.hdr.grayed = 0;
c_73205.tag = closureN_tag;
 c_73205.fn = (function_type)__lambda_2;
c_73205.num_args = 1;
c_73205.num_elements = 2;
c_73205.elements = (object *)alloca(sizeof(object) * 2);
c_73205.elements[0] = c_7341;
c_73205.elements[1] = k_73143;

return_closcall2(data,  __glo_char_91upper_91case_127_scheme__char,  &c_73205, c_7341);; 
}

static void __lambda_2(void *data, int argc, object self_73176, object r_73144) {
  if( (boolean_f != r_73144) ){ 
  
common_type local_73219; object c_73220 = Cyc_fast_sub(data,&local_73219,Cyc_char2integer(obj_char2obj(97)), Cyc_char2integer(obj_char2obj(65)));

common_type local_73212; object c_73213 = Cyc_fast_sum(data,&local_73212,Cyc_char2integer(((closureN)self_73176)->elements[0]), c_73220);
return_closcall1(data,  ((closureN)self_73176)->elements[1],  Cyc_integer2char(data, c_73213));
} else { 
  return_closcall1(data,  ((closureN)self_73176)->elements[1],  ((closureN)self_73176)->elements[0]);}
; 
}

static void __lambda_1(void *data, int argc, closure _,object k_73152, object c_7342) {
  Cyc_st_add(data, "scheme/char.sld:char-upcase");

closureN_type c_73180;
c_73180.hdr.mark = gc_color_red;
 c_73180.hdr.grayed = 0;
c_73180.tag = closureN_tag;
 c_73180.fn = (function_type)__lambda_0;
c_73180.num_args = 1;
c_73180.num_elements = 2;
c_73180.elements = (object *)alloca(sizeof(object) * 2);
c_73180.elements[0] = c_7342;
c_73180.elements[1] = k_73152;

return_closcall2(data,  __glo_char_91lower_91case_127_scheme__char,  &c_73180, c_7342);; 
}

static void __lambda_0(void *data, int argc, object self_73177, object r_73153) {
  if( (boolean_f != r_73153) ){ 
  
common_type local_73194; object c_73195 = Cyc_fast_sub(data,&local_73194,Cyc_char2integer(obj_char2obj(97)), Cyc_char2integer(obj_char2obj(65)));

common_type local_73187; object c_73188 = Cyc_fast_sub(data,&local_73187,Cyc_char2integer(((closureN)self_73177)->elements[0]), c_73195);
return_closcall1(data,  ((closureN)self_73177)->elements[1],  Cyc_integer2char(data, c_73188));
} else { 
  return_closcall1(data,  ((closureN)self_73177)->elements[1],  ((closureN)self_73177)->elements[0]);}
; 
}

void c_scheme_char_inlinable_lambdas(void *data, int argc, closure _, object cont){ 
make_pair(pair_73442, find_or_add_symbol("char-lower-case?"), find_or_add_symbol("char-lower-case?__inline__"));
make_pair(pair_73443, find_or_add_symbol("char-upper-case?"), find_or_add_symbol("char-upper-case?__inline__"));
make_pair(c_73444, &pair_73442, NULL);
make_pair(c_73445, &pair_73443, &c_73444);
(((closure)cont)->fn)(data, 1, cont, &c_73445);
 } 
void c_scheme_char_entry_pt_first_lambda(data, argc, cont,value) void *data; int argc; closure cont; object value;{ 

  add_global((object *) &__glo_lib_91init_117scheme_191char_scheme__char);
  add_global((object *) &__glo_string_91foldcase_scheme__char);
  add_global((object *) &__glo_string_91downcase_scheme__char);
  add_global((object *) &__glo_string_91upcase_scheme__char);
  add_global((object *) &__glo_digit_91value_scheme__char);
  add_global((object *) &__glo_char_91whitespace_127_scheme__char);
  add_global((object *) &__glo_char_91numeric_127_scheme__char);
  add_global((object *) &__glo_char_91lower_91case_127_191_191inline_191_191_scheme__char);
  add_global((object *) &__glo_char_91lower_91case_127_scheme__char);
  add_global((object *) &__glo_char_91upper_91case_127_191_191inline_191_191_scheme__char);
  add_global((object *) &__glo_char_91upper_91case_127_scheme__char);
  add_global((object *) &__glo_char_91alphabetic_127_scheme__char);
  add_global((object *) &__glo_string_91ci_125_123_127_scheme__char);
  add_global((object *) &__glo_string_91ci_125_127_scheme__char);
  add_global((object *) &__glo_string_91ci_121_123_127_scheme__char);
  add_global((object *) &__glo_string_91ci_121_127_scheme__char);
  add_global((object *) &__glo_string_91ci_123_127_scheme__char);
  add_global((object *) &__glo_char_91ci_125_127_scheme__char);
  add_global((object *) &__glo_char_91ci_125_123_127_scheme__char);
  add_global((object *) &__glo_char_91ci_121_127_scheme__char);
  add_global((object *) &__glo_char_91ci_121_123_127_scheme__char);
  add_global((object *) &__glo_char_91ci_123_127_scheme__char);
  add_global((object *) &__glo_char_91foldcase_scheme__char);
  add_global((object *) &__glo_char_91downcase_scheme__char);
  add_global((object *) &__glo_char_91upcase_scheme__char);
  mclosure0(c_73438, (function_type)__lambda_42);c_73438.num_args = 0; 
  __glo_lib_91init_117scheme_191char_scheme__char = &c_73438; 
  mclosure0(c_73436, (function_type)__lambda_41);c_73436.num_args = 1; 
  __glo_string_91foldcase_scheme__char = &c_73436; 
  mclosure0(c_73434, (function_type)__lambda_40);c_73434.num_args = 1; 
  __glo_string_91downcase_scheme__char = &c_73434; 
  mclosure0(c_73432, (function_type)__lambda_39);c_73432.num_args = 1; 
  __glo_string_91upcase_scheme__char = &c_73432; 
  mclosure0(c_73416, (function_type)__lambda_38);c_73416.num_args = 1; 
  __glo_digit_91value_scheme__char = &c_73416; 
  mclosure0(c_73407, (function_type)__lambda_36);c_73407.num_args = 1; 
  __glo_char_91whitespace_127_scheme__char = &c_73407; 
  mclosure0(c_73392, (function_type)__lambda_35);c_73392.num_args = 1; 
  __glo_char_91numeric_127_scheme__char = &c_73392; 
  mclosure0(c_73383, (function_type)__lambda_34);c_73383.num_args = 1; 
  __glo_char_91lower_91case_127_191_191inline_191_191_scheme__char = &c_73383; 
  mclosure0(c_73374, (function_type)__lambda_33);c_73374.num_args = 1; 
  __glo_char_91lower_91case_127_scheme__char = &c_73374; 
  mclosure0(c_73365, (function_type)__lambda_32);c_73365.num_args = 1; 
  __glo_char_91upper_91case_127_191_191inline_191_191_scheme__char = &c_73365; 
  mclosure0(c_73356, (function_type)__lambda_31);c_73356.num_args = 1; 
  __glo_char_91upper_91case_127_scheme__char = &c_73356; 
  mclosure0(c_73348, (function_type)__lambda_30);c_73348.num_args = 1; 
  __glo_char_91alphabetic_127_scheme__char = &c_73348; 
  mclosure0(c_73338, (function_type)__lambda_28);c_73338.num_args = 2; 
  __glo_string_91ci_125_123_127_scheme__char = &c_73338; 
  mclosure0(c_73328, (function_type)__lambda_25);c_73328.num_args = 2; 
  __glo_string_91ci_125_127_scheme__char = &c_73328; 
  mclosure0(c_73318, (function_type)__lambda_22);c_73318.num_args = 2; 
  __glo_string_91ci_121_123_127_scheme__char = &c_73318; 
  mclosure0(c_73308, (function_type)__lambda_19);c_73308.num_args = 2; 
  __glo_string_91ci_121_127_scheme__char = &c_73308; 
  mclosure0(c_73298, (function_type)__lambda_16);c_73298.num_args = 2; 
  __glo_string_91ci_123_127_scheme__char = &c_73298; 
  mclosure0(c_73284, (function_type)__lambda_13);c_73284.num_args = 2; 
  __glo_char_91ci_125_127_scheme__char = &c_73284; 
  mclosure0(c_73270, (function_type)__lambda_11);c_73270.num_args = 2; 
  __glo_char_91ci_125_123_127_scheme__char = &c_73270; 
  mclosure0(c_73256, (function_type)__lambda_9);c_73256.num_args = 2; 
  __glo_char_91ci_121_127_scheme__char = &c_73256; 
  mclosure0(c_73242, (function_type)__lambda_7);c_73242.num_args = 2; 
  __glo_char_91ci_121_123_127_scheme__char = &c_73242; 
  mclosure0(c_73228, (function_type)__lambda_5);c_73228.num_args = 2; 
  __glo_char_91ci_123_127_scheme__char = &c_73228; 
  mclosure0(c_73203, (function_type)__lambda_3);c_73203.num_args = 1; 
  __glo_char_91downcase_scheme__char = &c_73203; 
  mclosure0(c_73178, (function_type)__lambda_1);c_73178.num_args = 1; 
  __glo_char_91upcase_scheme__char = &c_73178; 
  __glo_char_91foldcase_scheme__char = boolean_f; 

  mclosure0(clo_73447, c_scheme_char_inlinable_lambdas); make_pair(pair_73446, find_or_add_symbol("c_scheme_char_inlinable_lambdas"), &clo_73447);
  make_cvar(cvar_73448, (object *)&__glo_lib_91init_117scheme_191char_scheme__char);make_pair(pair_73449, find_or_add_symbol("lib-init:scheme_char"), &cvar_73448);
  make_cvar(cvar_73450, (object *)&__glo_string_91foldcase_scheme__char);make_pair(pair_73451, find_or_add_symbol("string-foldcase"), &cvar_73450);
  make_cvar(cvar_73452, (object *)&__glo_string_91downcase_scheme__char);make_pair(pair_73453, find_or_add_symbol("string-downcase"), &cvar_73452);
  make_cvar(cvar_73454, (object *)&__glo_string_91upcase_scheme__char);make_pair(pair_73455, find_or_add_symbol("string-upcase"), &cvar_73454);
  make_cvar(cvar_73456, (object *)&__glo_digit_91value_scheme__char);make_pair(pair_73457, find_or_add_symbol("digit-value"), &cvar_73456);
  make_cvar(cvar_73458, (object *)&__glo_char_91whitespace_127_scheme__char);make_pair(pair_73459, find_or_add_symbol("char-whitespace?"), &cvar_73458);
  make_cvar(cvar_73460, (object *)&__glo_char_91numeric_127_scheme__char);make_pair(pair_73461, find_or_add_symbol("char-numeric?"), &cvar_73460);
  make_cvar(cvar_73462, (object *)&__glo_char_91lower_91case_127_191_191inline_191_191_scheme__char);make_pair(pair_73463, find_or_add_symbol("char-lower-case?__inline__"), &cvar_73462);
  make_cvar(cvar_73464, (object *)&__glo_char_91lower_91case_127_scheme__char);make_pair(pair_73465, find_or_add_symbol("char-lower-case?"), &cvar_73464);
  make_cvar(cvar_73466, (object *)&__glo_char_91upper_91case_127_191_191inline_191_191_scheme__char);make_pair(pair_73467, find_or_add_symbol("char-upper-case?__inline__"), &cvar_73466);
  make_cvar(cvar_73468, (object *)&__glo_char_91upper_91case_127_scheme__char);make_pair(pair_73469, find_or_add_symbol("char-upper-case?"), &cvar_73468);
  make_cvar(cvar_73470, (object *)&__glo_char_91alphabetic_127_scheme__char);make_pair(pair_73471, find_or_add_symbol("char-alphabetic?"), &cvar_73470);
  make_cvar(cvar_73472, (object *)&__glo_string_91ci_125_123_127_scheme__char);make_pair(pair_73473, find_or_add_symbol("string-ci>=?"), &cvar_73472);
  make_cvar(cvar_73474, (object *)&__glo_string_91ci_125_127_scheme__char);make_pair(pair_73475, find_or_add_symbol("string-ci>?"), &cvar_73474);
  make_cvar(cvar_73476, (object *)&__glo_string_91ci_121_123_127_scheme__char);make_pair(pair_73477, find_or_add_symbol("string-ci<=?"), &cvar_73476);
  make_cvar(cvar_73478, (object *)&__glo_string_91ci_121_127_scheme__char);make_pair(pair_73479, find_or_add_symbol("string-ci<?"), &cvar_73478);
  make_cvar(cvar_73480, (object *)&__glo_string_91ci_123_127_scheme__char);make_pair(pair_73481, find_or_add_symbol("string-ci=?"), &cvar_73480);
  make_cvar(cvar_73482, (object *)&__glo_char_91ci_125_127_scheme__char);make_pair(pair_73483, find_or_add_symbol("char-ci>?"), &cvar_73482);
  make_cvar(cvar_73484, (object *)&__glo_char_91ci_125_123_127_scheme__char);make_pair(pair_73485, find_or_add_symbol("char-ci>=?"), &cvar_73484);
  make_cvar(cvar_73486, (object *)&__glo_char_91ci_121_127_scheme__char);make_pair(pair_73487, find_or_add_symbol("char-ci<?"), &cvar_73486);
  make_cvar(cvar_73488, (object *)&__glo_char_91ci_121_123_127_scheme__char);make_pair(pair_73489, find_or_add_symbol("char-ci<=?"), &cvar_73488);
  make_cvar(cvar_73490, (object *)&__glo_char_91ci_123_127_scheme__char);make_pair(pair_73491, find_or_add_symbol("char-ci=?"), &cvar_73490);
  make_cvar(cvar_73492, (object *)&__glo_char_91foldcase_scheme__char);make_pair(pair_73493, find_or_add_symbol("char-foldcase"), &cvar_73492);
  make_cvar(cvar_73494, (object *)&__glo_char_91downcase_scheme__char);make_pair(pair_73495, find_or_add_symbol("char-downcase"), &cvar_73494);
  make_cvar(cvar_73496, (object *)&__glo_char_91upcase_scheme__char);make_pair(pair_73497, find_or_add_symbol("char-upcase"), &cvar_73496);
make_pair(c_73498, &pair_73446,Cyc_global_variables);
make_pair(c_73499, &pair_73449, &c_73498);
make_pair(c_73500, &pair_73451, &c_73499);
make_pair(c_73501, &pair_73453, &c_73500);
make_pair(c_73502, &pair_73455, &c_73501);
make_pair(c_73503, &pair_73457, &c_73502);
make_pair(c_73504, &pair_73459, &c_73503);
make_pair(c_73505, &pair_73461, &c_73504);
make_pair(c_73506, &pair_73463, &c_73505);
make_pair(c_73507, &pair_73465, &c_73506);
make_pair(c_73508, &pair_73467, &c_73507);
make_pair(c_73509, &pair_73469, &c_73508);
make_pair(c_73510, &pair_73471, &c_73509);
make_pair(c_73511, &pair_73473, &c_73510);
make_pair(c_73512, &pair_73475, &c_73511);
make_pair(c_73513, &pair_73477, &c_73512);
make_pair(c_73514, &pair_73479, &c_73513);
make_pair(c_73515, &pair_73481, &c_73514);
make_pair(c_73516, &pair_73483, &c_73515);
make_pair(c_73517, &pair_73485, &c_73516);
make_pair(c_73518, &pair_73487, &c_73517);
make_pair(c_73519, &pair_73489, &c_73518);
make_pair(c_73520, &pair_73491, &c_73519);
make_pair(c_73521, &pair_73493, &c_73520);
make_pair(c_73522, &pair_73495, &c_73521);
make_pair(c_73523, &pair_73497, &c_73522);
Cyc_global_variables = &c_73523;
cont = ((closure1_type *)cont)->element;
(((closure)__glo_lib_91init_117scheme_191char_scheme__char)->fn)(data, 1, cont, cont);
}
void c_scheme_char_entry_pt(data, argc, cont,value) void *data; int argc; closure cont; object value;{ 
  register_library("scheme__char");
  c_scheme_char_entry_pt_first_lambda(data, argc, cont,value);
}
